### ISSUE TITLE
Add a New Page for "Dine-in" , where users will find their Nearest Resturants ( only Front-end)

### ISSUE THREAD

**Issue by Sapta-Dev27** [DharshiBalasubramaniyam/ice-cream-parlour-website#10]

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Sapta-Dev27, Thank you for creating this issue. Can you please explain the content of the page or provide any screenshot?

**Comment by Sapta-Dev27** [comment]
@DharshiBalasubramaniyam  yeah ofc !!
I will make a Page where users will be able to see their nearest dine-in Resturants :
Features 👍 
1. A search Bar ( with Location Icon)
2. A Resturant section acc to the ENTERED Location ( I wilol be dyanimally adding images as of now) cause at present I am focusing on the Front-end part of the page 
3. A reviews section
4. A Proper Footer


These are the Features of the PAGE ..I am sorry that I couldn't provide u with a UI of the Page rn !!

**Comment by AkankshaSinghK** [comment]
I would like to work on implementing the Dine-in page for this website, which will allow users to find their nearest dine-in restaurants.

Features:
Search Bar with a location icon, allowing users to enter their location.
Restaurant Section: Based on the entered location, dynamically display restaurants with placeholder images for now.
Reviews Section: Display customer reviews for the dine-in restaurants.
Footer: A proper footer for the page, including necessary information.

Kindly assign this to me.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam yeah ofc !! I will make a Page where users will be able to see their nearest dine-in Resturants : Features 👍
> 
> 1. A search Bar ( with Location Icon)
> 2. A Resturant section acc to the ENTERED Location ( I wilol be dyanimally adding images as of now) cause at present I am focusing on the Front-end part of the page
> 3. A reviews section
> 4. A Proper Footer
> 
> These are the Features of the PAGE ..I am sorry that I couldn't provide u with a UI of the Page rn !!

Alright... carry on. Kindly please add the same nav, cart and the footer used in the `index.html`. If you meet any trouble with displaying cart modal, leave it. I'll manage it.

**Comment by Sapta-Dev27** [comment]
@DharshiBalasubramaniyam have you merged my PR yet ....cause I am seeing you CLOSED my issue after ASSIGNING it to me ..
I think you should be responsible enough to inform the CONTRIBUTER if u are CLOSING an ISSUE after assigning it to someone who had already made the PR and solved the issue ...Kindly check this from the next time and if possible MERGE my PR !!
