### ISSUE TITLE
An overlay Screen appears when feedback is submitted saying "Thanks for your Feedback"

### ISSUE THREAD

**Issue by aadiishivhare** [DharshiBalasubramaniyam/ice-cream-parlour-website#1001]
An overlay Screen appears when feedback is submitted saying "Thanks for submitting your Feedback"
and then disappears after 5 seconds, letting user know that his feedback is submitted.

**Comment by veepanshu-kasana** [comment]
@DharshiBalasubramaniyam i want to work on this issue please assign it to me under gssoc-ext 2024
