### ISSUE TITLE
[Feat]: add chatbot integration to website

### ISSUE THREAD

**Issue by Ankul8471** [DharshiBalasubramaniyam/ice-cream-parlour-website#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add chatbot integration to website

### Use Case

add chatbot integration to website

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Ankul8471** [comment]
@DharshiBalasubramaniyam  please assign me this issue

**Comment by Gungunmi12** [comment]
can u assign this issue to me
