### ISSUE TITLE
Popup on home page is not responsive

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#1010]
To maintain responsive, remove the image in the left side in mobile view.

<img width="208" alt="image" src="https://github.com/user-attachments/assets/71d8952d-b092-4147-b896-9db078c462a8">

**Comment by Arshia-163** [comment]
Please check #1017

**Comment by BhavikaPachauri** [comment]
I would like to solve this issue

**Comment by arorasneha08** [comment]
please assign this issue to me
