### ISSUE TITLE
[Feat]: TWITTER LOGO NEED TO BE ADDED IN FOOTER SECTION

### ISSUE THREAD

**Issue by likitha-kapu** [DharshiBalasubramaniyam/ice-cream-parlour-website#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the footer section includes social media links but is missing a Twitter logo, making it incomplete for users who may want to connect via Twitter.

### Use Case

Adding the Twitter logo in the footer would enhance the project by making it easier to connect with users across all major social media platforms directly from our site. This feature ensures consistency, helping build a stronger online presence and encouraging users to engage with us on Twitter without needing to search elsewhere. It provides a seamless, professional user experience and aligns the project with modern web standards, boosting both usability and brand visibility.

### Benefits

Adding the Twitter logo in the footer enhances user engagement, brand visibility, and community connectivity by providing easy access to updates and interactions on social media.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by likitha-kapu** [comment]
![Screenshot 2024-10-30 162907](https://github.com/user-attachments/assets/28d6424b-e414-4885-b347-20319a3b7d17)

**Comment by likitha-kapu** [comment]
@DharshiBalasubramaniyam  assign this task to me

**Comment by DharshiBalasubramaniyam** [comment]
@likitha-kapu pls do it in all pages.

**Comment by likitha-kapu** [comment]
@DharshiBalasubramaniyam can u add a level2 label

**Comment by likitha-kapu** [comment]
@DharshiBalasubramaniyam please checkout my pull request and assign me a level2 label
