### ISSUE TITLE
[Bug]: in contact page Input Validation

### ISSUE THREAD

**Issue by anish013326** [DharshiBalasubramaniyam/ice-cream-parlour-website#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add Screenshots

![image](https://github.com/user-attachments/assets/28be7c00-3df2-48c0-98e1-11f9a72298bc)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by arorasneha08** [comment]
Plz assign this task to me
