### ISSUE TITLE
Improving the Contact section

### ISSUE THREAD

**Issue by NishantK-07** [DharshiBalasubramaniyam/ice-cream-parlour-website#103]
The contact section page can be improved and can be made more interactive 
![Screenshot 2024-10-04 095333](https://github.com/user-attachments/assets/e7cd57f2-317c-4418-a05a-9f792b159422)

**Comment by NishantK-07** [comment]
Please assign this issue to me ...under gssoc 2024 extended

**Comment by jyothimanoj12** [comment]
plz assign me this issue

**Comment by PulkitShubham** [comment]
Hello @DharshiBalasubramaniyam............Nothing is happening when I click on send
![Uploading Screenshot (225).png…]()
 button....kindly assign me this issue I would like to work on it

**Comment by PulkitShubham** [comment]
Hello @DharshiBalasubramaniyam............Nothing is happening when I click on send 
![Screenshot (225)](https://github.com/user-attachments/assets/544cb12f-562c-4278-8ee3-2a06b1641a5e)
button....kindly assign me this issue I would like to work on it
