### ISSUE TITLE
Twitter logo is missing and misalignment of the word

### ISSUE THREAD

**Issue by Utkarsha156** [DharshiBalasubramaniyam/ice-cream-parlour-website#1031]
The logo of twitter is missing and it is misaligned due to that
![image](https://github.com/user-attachments/assets/7c5a3d00-8710-448a-a833-0e8c628b75c4)

can you assign me this issue @DharshiBalasubramaniyam

**Comment by Arghya-Chakraborty0812** [comment]
Please assign this issue to me @DharshiBalasubramaniyam
