### ISSUE TITLE
Footer section not covering the entire screen 

### ISSUE THREAD

**Issue by Utkarsha156** [DharshiBalasubramaniyam/ice-cream-parlour-website#1032]
There is  gap between the footer section and the screen in the righthand side making it unappealing. It should cover the whole screen.
I can fix this. Will you please assign me this @DharshiBalasubramaniyam ?

![image](https://github.com/user-attachments/assets/18871487-4066-4592-aa77-954829e34cd6)

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it
