### ISSUE TITLE
[Feat]: Add a home button in login page.

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [DharshiBalasubramaniyam/ice-cream-parlour-website#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Missing home icon in the login page

### Use Case

The home icon will allow you to navigate back to the home page and enhance user experience.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it
