### ISSUE TITLE
[Feat]: Adding Contact us button in Navbar

### ISSUE THREAD

**Issue by Prachiikhar25** [DharshiBalasubramaniyam/ice-cream-parlour-website#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![{60ADE6A0-0024-45D8-B4DF-D6476BF17A44}](https://github.com/user-attachments/assets/d7bd6ab2-a6d1-49bf-aa12-a0b890acd161)
I'd like to add details and contact button in the navbar.
I can add Signup and Login button too if you please.

Thanks!

### Use Case

Adding Contact us button would make it reachable for customers, and easy to contact for gathering pre info.
I'd like to add contact us button on navbar.

### Benefits

Adding this feature would make the website accountable and feasible,
Indeed easy to make contact with the shop.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Vijeth-Kumar-18** [comment]
I wou;d like to add contact us navbar and contact us page to this repo. Please assign it to me
