### ISSUE TITLE
Improving the FAQ's section 

### ISSUE THREAD

**Issue by NishantK-07** [DharshiBalasubramaniyam/ice-cream-parlour-website#104]
The FAQ's can be improved like making it similar to Netflix's FAQ's section
![Screenshot 2024-10-04 095737](https://github.com/user-attachments/assets/c1994e44-0703-43b3-87e8-7b5376f3db6e)
![Screenshot 2024-10-04 095350](https://github.com/user-attachments/assets/ff12c34c-5e10-4bf9-8f2a-36680bb6be82)

**Comment by NishantK-07** [comment]
Please assign this issue to me under ... gssoc 2024 extended

**Comment by rupeshv2121** [comment]
I love to solve this issue , If possible Please assign me this task
