### ISSUE TITLE
Add a home/back button in the login page

### ISSUE THREAD

**Issue by Antima2004** [DharshiBalasubramaniyam/ice-cream-parlour-website#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This PR addresses the issue of adding "Back" and "Home" buttons on the login page to improve navigation for users. The Back button allows users to return to the previous page, and the Home button takes them directly to the home page.

### Use Case

To provide users with an easy way to return to the previous page or go directly to the homepage from the login page, enhancing the user experience and navigation flow.

Primary Actor
User: Any user accessing the login page, which may include new visitors, returning users, or customers who wish to navigate back or directly to the homepage.
Preconditions
The user has navigated to the login page from any other page within the application or from an external link.
The application has a defined homepage and other navigable pages.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ayudixit** [comment]
Hello, Assign me this issue to resolve.

**Comment by Antima2004** [comment]
Ok

**Comment by ayudixit** [comment]
Thanks for the reply @DharshiBalasubramaniyam make me Assignee for this issue.

**Comment by ambrishgoswami** [comment]
plz assign this issue
