### ISSUE TITLE
Creation of Login Page and Profile Page

### ISSUE THREAD

**Issue by Nitin8426** [DharshiBalasubramaniyam/ice-cream-parlour-website#111]
![Screenshot 2024-10-04 132040](https://github.com/user-attachments/assets/0bc0f6f9-b9c3-4c01-8182-1400336386de)
 Create and  implement the Login Page and Profile Page for our ice cream parlour website. This will allow customers to log in, manage their profiles, and view/update their personal information.

Tasks:

Login Page:

Design and develop the login interface.
Include fields for email/username and password.
Add "Forgot Password" and "Sign Up" links.
Ensure validation for form fields.
Implement error handling for incorrect login credentials.
Redirect users to the Profile Page upon successful login.
Profile Page:

Display the user's personal details (name, email, phone number, etc.).
Provide an option to edit/update personal information.
Add a "Change Password" option.
Include a "Log Out" button to end the session.
Design the page with a user-friendly and responsive layout.

Assign me this issue under hacktoberfest and GSSoC extended 2024 .

**Comment by DharshiBalasubramaniyam** [comment]
Kindly check existing issues before raising new. These are already assined to someone
