### ISSUE TITLE
Non functional Catering section in main page

### ISSUE THREAD

**Issue by 1ShahidBashir** [DharshiBalasubramaniyam/ice-cream-parlour-website#117]
The catering section in the main page, where the user is supposed to write about the event and its details is non functional.
![Screenshot from 2024-10-04 15-35-56](https://github.com/user-attachments/assets/8c7d3112-7a6f-4d3f-b2d4-f7b0eacd8924)
A new webpage can be added for catering an event

**Comment by 1ShahidBashir** [comment]
assign this issue to me @DharshiBalasubramaniyam I can work this one out

**Comment by DharshiBalasubramaniyam** [comment]
Under this I have some suggestions:
I want to create a page for caterings as same as `delivery/html`. 
keep nav, footer, styles and scripts as same as `delivery/html`. 
Update the headings and form as below image.

![Screenshot (46)](https://github.com/user-attachments/assets/24388120-edb5-41ef-8757-21594a54df0a)

Can you do it @1ShahidBashir ?

**Comment by 1ShahidBashir** [comment]
yes @DharshiBalasubramaniyam I will

**Comment by DharshiBalasubramaniyam** [comment]
> hey @DharshiBalasubramaniyam Is this good? ![Screenshot from 2024-10-05 17-38-32](https://private-user-images.githubusercontent.com/101783159/373870207-72eedfc3-3627-48c4-afc7-5b6897b8773e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzU3ODcsIm5iZiI6MTcyODEzNTQ4NywicGF0aCI6Ii8xMDE3ODMxNTkvMzczODcwMjA3LTcyZWVkZmMzLTM2MjctNDhjNC1hZmM3LTViNjg5N2I4NzczZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2MxNjBhMGEwYmI1OTBhMDIzZTVkODNhNzQyNWVmMWE0MzZkYjEzOTg2YzVkNGMwYjI0MjQ4OWM3MjRiMzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n0f3bkOknmM3lIrpvFUIjE4FndvHmozh0ENwS_ySMkc) ![Screenshot from 2024-10-05 17-38-43](https://private-user-images.githubusercontent.com/101783159/373870233-a4a15d3d-cbc8-442c-89f1-2daa4ef3933c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzU3ODcsIm5iZiI6MTcyODEzNTQ4NywicGF0aCI6Ii8xMDE3ODMxNTkvMzczODcwMjMzLWE0YTE1ZDNkLWNiYzgtNDQyYy04OWYxLTJkYWE0ZWYzOTMzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMzM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGUyYzQ5NGFjMjkyMjNkMDIxYjc0MzhmMzk2OWMzMzE5NDdmYTA2ODM3MjZhN2IxODk5YTgyOGZlM2M1YjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qCVuCat99uzWjcLbz9NYeIcMn7VxCtvByLR1FJoE2AI) I can also provide the changes I made to styles.css because i needed different css for radio input in the form of catering :)

Yeah cool!

**Comment by 1ShahidBashir** [comment]
@DharshiBalasubramaniyam  I have made a PR could you please check it!
