### ISSUE TITLE
Add a New Page for " Catering" where people will be able to book their CATERINGS  (Front-end)

### ISSUE THREAD

**Issue by Sapta-Dev27** [DharshiBalasubramaniyam/ice-cream-parlour-website#12]

**Comment by Ibrangrd** [comment]
I will create a attractive page . Give me a chance .

**Comment by clownfish1805** [comment]
@DharshiBalasubramaniyam 
I would like to work on creating a new page for catering where people will be able to book their CATERINGS.

Features includes 👍 

1. Header section
2. Would create a multi-step form wizard (one step at a time for ease). For example:
Step 1: Event details.
Step 2: Menu selection.
Step 3: Venue setup.
Step 4: Additional services and summary.
Each step would appear on the same page, but users navigate through steps by clicking "Next" or "Back". 
4. Submit button
3.Footer section

**Comment by DharshiBalasubramaniyam** [comment]
Already assigned for another person. Before creating issues, Kindly Go through the existing issues
