### ISSUE TITLE
[BUG] Nav bar links missing

### ISSUE THREAD

**Issue by 4F24L** [DharshiBalasubramaniyam/ice-cream-parlour-website#120]
## The links in the navigation bar are not working.
- [ Home | Service | About | Products | Review | Contact ]
- These links are not working.

- https://ice-cream-parlour-website-one.vercel.app [ Confirm the issue ]

## Screenshot : 
![Screenshot 2024-10-04 175617](https://github.com/user-attachments/assets/1ef4f8da-7093-414b-b658-3ad8f5bea356)

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @4F24L, I think now the issue is sorted out.
