### ISSUE TITLE
Enhancement : alert message can be changed to something better

### ISSUE THREAD

**Issue by sriraghavi22** [DharshiBalasubramaniyam/ice-cream-parlour-website#124]
The current cart notification method is a basic alert message, which can be improved for a better user experience. Instead of using a standard alert, I propose implementing a more interactive and visually engaging notification method when items are added to the cart. 

https://github.com/user-attachments/assets/c47f4038-5981-40e2-9f01-40dbbfcd1044

I would like to work on this issue

**Comment by DharshiBalasubramaniyam** [comment]
@sriraghavi22 Can you explain me how you will improve the ux regarding this?

**Comment by sriraghavi22** [comment]
A small popup in the corner that auto-hides after a few seconds, or a modal showing confirmation and options to continue shopping or view the cart.
or else if u want anything specific i would like to implement it.

**Comment by DharshiBalasubramaniyam** [comment]
This one is okay -> A small popup in the corner that auto-hides after a few seconds.
