### ISSUE TITLE
[Add feature]: Improve the cursor

### ISSUE THREAD

**Issue by Amulya-B28** [DharshiBalasubramaniyam/ice-cream-parlour-website#125]
I would like to change cursor to something better....please assign this task to me.

![image](https://github.com/user-attachments/assets/a144debb-f21f-4198-8b79-c9a532d0861f)

**Comment by soumyajit254** [comment]
I want to contribute. Please assign me

**Comment by Amulya-B28** [comment]
![image](https://github.com/user-attachments/assets/739addce-0a32-4ba5-ace0-f29e048d5858)
 @DharshiBalasubramaniyam Few hours left before this pull request is verified.....So can you please merge this pull request.....hoping for a positive response....Thank you.
