### ISSUE TITLE
Login/signup functionality missing

### ISSUE THREAD

**Issue by aditya07389** [DharshiBalasubramaniyam/ice-cream-parlour-website#126]
Hello there! @DharshiBalasubramaniyam  I’ve been going through your project, and the work done so far is truly impressive. However, I noticed that there’s currently no signup functionality available. 

I’d be happy to implement it for you. Having a login/signup system would make it much easier for users to track their orders, ensuring they are well-organized, especially when ordering ice cream.

Could you please assign this issue to me?

**P.S.** Please add the labels `gssoc extended` and `hacktoberfest`. 

Thank you!

**Comment by DharshiBalasubramaniyam** [comment]
Already added!
