### ISSUE TITLE
improvement in contact us design 

### ISSUE THREAD

**Issue by jonjonjonjo** [DharshiBalasubramaniyam/ice-cream-parlour-website#127]
the component of contact us can be improved  a bit and the design of cursor can also be changed which will maek the website more attractive.

Given my decent experince in html, css, javascript, i request u to assign this task to me.

**Comment by Renu1418** [comment]
Hi, I would like to work on improving the design of the "Contact Us" page using HTML and CSS only. Here's my plan for the improvements:

1. I will enhance the layout with clean and responsive HTML structure.
2. I will improve the CSS styling by adding modern design elements like better spacing, font choices, and form styling (input boxes, labels, and buttons).
3. I plan to make the design more visually appealing by improving the color scheme and typography.

These improvements will enhance the user experience while keeping the design consistent with the rest of the site. Could you please assign this issue to me? I would love to contribute!

**Comment by DharshiBalasubramaniyam** [comment]
Already assigned to another contributor!
