### ISSUE TITLE
Some Additional Feature Add to Website.

### ISSUE THREAD

**Issue by 13Sharad** [DharshiBalasubramaniyam/ice-cream-parlour-website#128]
First : - If Website is Open then Ice Cream Staring Moving Upward and Downward, but this change to if cursor come to ice-cream image then ice-cream moves upward or downward. This change improved the website more user-friendly.

Second : - Add moving feature in Top Reviews card that show ui more user-friendly.

ScreenShort : - 

![Screenshot 2024-10-04 192253](https://github.com/user-attachments/assets/1135a5a9-3c75-49d1-a5d7-0e41b24cebfb)

Adding this feature in Top Reviews card section. 
videoShort : - 

https://github.com/user-attachments/assets/36a75786-0d27-4c74-954b-7d1e32437b71

Third : -  Scoop into Happiness, Anytime, Anywhere! This heading para or many heading para cursor should be selected. Cursor should not be select some heading para or many para such as What we do?,About Us,Our Products,Top Reviews,Contact Us,FAQs. this small change improved the website more friendly. 

Fourth : - Adding some feature in Our Products section. such as

videoShort :- 
 
https://github.com/user-attachments/assets/882531a9-e40d-4f95-a455-15d3c1eb15c1

Please Assign me to Resolved all issue.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
