### ISSUE TITLE
Enhance Navigation Bar Design with Transform Effects and Improved Typography

### ISSUE THREAD

**Issue by Renu1418** [DharshiBalasubramaniyam/ice-cream-parlour-website#129]
I would like to propose enhancements to the navigation bar to improve the user experience and visual appeal. The changes I plan to implement include:

1. **Font Size Adjustment**: Increase the font size for better readability and accessibility.
2. **Transform Effects**: 
   - Add a subtle transform effect to the nav bar items on hover to scale them up slightly, providing a more interactive feel.
3. **Shadow Effect**: Add a slight shadow effect to the nav items to create depth and separation from the background.
4. **Smooth Transition**: Use CSS transitions to ensure that all changes occur smoothly for a better user experience.

I believe these enhancements will make the navigation bar more engaging and user-friendly. I am excited to contribute and would love to take this issue on!

**Comment by Renu1418** [comment]
@DharshiBalasubramaniyam I am waiting for you to assign this to me.

**Comment by Renu1418** [comment]
@DharshiBalasubramaniyam  I wanted to inform you about the recent enhancements I made to the project. Here are the key updates:
1. Hover Effect: I have implemented a transform effect on hover for various elements. This effect provides a smooth transition, making the interface more interactive and visually appealing.

2. Font Size Increase: I increased the font size across the website to improve readability. This change ensures that users can easily read the content without straining their eyes.

3. Font Family Change: I also changed the font family to a more user-friendly option. This adjustment enhances the overall aesthetics and contributes to a better reading experience for our users.

I believe these changes will significantly enhance user engagement and satisfaction. If you have any questions or need further modifications, please let me know.

please assign this to me .
<img width="957" alt="ice-cream ss" src="https://github.com/user-attachments/assets/592e1e0d-b020-4461-993a-36ca9277145e">

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
