### ISSUE TITLE
In product page, set default Quantity 1 instead of 0

### ISSUE THREAD

**Issue by Amanjayswal500** [DharshiBalasubramaniyam/ice-cream-parlour-website#136]
When the user clicks add to cart at least 1 item is added. It increases the sales and it doesn't make sense to add 0 items in the cart or send a popup message. 

![Screenshot 2024-10-05 011527](https://github.com/user-attachments/assets/59056886-aee3-4988-b6b0-987c378c5aa8)

**Comment by Amanjayswal500** [comment]
@DharshiBalasubramaniyam waiting to be assigned!

**Comment by Akanshaku** [comment]
pls assign me this issue I will surely resolve it.

**Comment by Mirnalkishor** [comment]
I want to work on this issue.please assign this me.
