### ISSUE TITLE
Adding Contributors' Profile Photos

### ISSUE THREAD

**Issue by souvikpramanikgit** [DharshiBalasubramaniyam/ice-cream-parlour-website#140]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared

Hey! @devxMani I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it
![image](https://github.com/user-attachments/assets/76171289-5b05-48c4-a5be-dc8ac76d70cb)

**Comment by devxMani** [comment]
@souvikpramanikgit @DharshiBalasubramaniyam don't do this for any issue admin has to give 2-3 days at least
