### ISSUE TITLE
the "tell us about your event" option in not responsive.

### ISSUE THREAD

**Issue by sakshamsaraf23** [DharshiBalasubramaniyam/ice-cream-parlour-website#142]
@DharshiBalasubramaniyam the "tell us about your event" option is not responsive and i checked there is no page linked to it, so if u want i can design a fontend for the same

**Comment by vikas83pal** [comment]
@DharshiBalasubramaniyam I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!

**Comment by DharshiBalasubramaniyam** [comment]
Now solved!
