### ISSUE TITLE
Improvement or change is required in Font Choice and Size

### ISSUE THREAD

**Issue by Durga200422** [DharshiBalasubramaniyam/ice-cream-parlour-website#143]
@DharshiBalasubramaniyam

Current Font is bold, playful font suits the theme, but it could be a bit overwhelming in large paragraphs. We can improve by using  a more elegant and readable font for the body text (e.g., "Poppins," "Roboto," or "Lato"). it means Keeping the fun font for headlines, but balancing it with a lighter-weight text for descriptions.

Please assign me the issue, i would like to work on it
![image](https://github.com/user-attachments/assets/c5180f1c-311d-42ff-aab8-3d9e9de8b001)

**Comment by Vipulsnips** [comment]
Hi @DharshiBalasubramaniyam I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!

**Comment by vikas83pal** [comment]
Hi @DharshiBalasubramaniyam  I would like to work on this issue. Could you please assign me this task 
 Thanks

**Comment by DarakshanSaara** [comment]
@DharshiBalasubramaniyam Could you assign this issue to me as I can make its font more better

**Comment by DharshiBalasubramaniyam** [comment]
Already assigned to others
