### ISSUE TITLE
[BUG] : FAQ Section (Active State)

### ISSUE THREAD

**Issue by Someshog** [DharshiBalasubramaniyam/ice-cream-parlour-website#154]
#
## Steps to Reproduce:

1) Navigate to the FAQ section of the application.
2) Click on the first question to expand it.
3) Click on a second question to expand it while the first one is still open (the bug).

**Expected Behavior:** When a new question is opened, the previously active question should close automatically.
**Actual Behavior:** Both questions remain active (expanded) simultaneously.

## Screenshots:
Here the 2 FAQ's are ACTIVE AT THE SAME TIME 

<img width="329" alt="faqbug1" src="https://github.com/user-attachments/assets/7ced5e7a-7801-470b-9f15-14ea5acf7119">

### _Additional Information:_
This bug affects the user experience by causing confusion and making it difficult to read the answers. A fix would enhance the FAQ usability and more readability.

**Please assign I would like to contribute <3**

**Comment by iamprathama** [comment]
i want to contribute

**Comment by Codersweta7** [comment]
@Someshog 
Please tell me the command to clone this in my system , I am not able to clone this repository if cloning happens then also 50%

**Comment by Someshog** [comment]
@Codersweta7 

1) Make sure you have git installed by running: `git --version`
2) Fork the repository 
3) Clone the forked repository as: `git clone https://github.com/<your-username>/<repository-name>.git`

**Comment by Codersweta7** [comment]
> @Codersweta7
> 
> 1. Make sure you have git installed by running: `git --version`
> 2. Fork the repository
> 3. Clone the forked repository as: `git clone https://github.com/<your-username>/<repository-name>.git`

Tell me the command git clone ........which you typed to clone this repository

**Comment by iamprathama** [comment]
![Screenshot 2024-10-06 152003](https://github.com/user-attachments/assets/9530d2bb-b224-486b-9a45-cc565b1c9726)
![Screenshot 2024-10-06 152037](https://github.com/user-attachments/assets/4483338b-63d1-44e6-a9b1-a8a1288b2ce9)
1. i solve your problem fixed bug
2. 
![Screenshot 2024-10-06 152003](https://github.com/user-attachments/assets/45080810-1128-472f-9ab0-5797b6b09831)
@Someshog @ # 
[README.md](https://github.com/user-attachments/files/17268832/README.md)
