### ISSUE TITLE
Add FAQ Section for Ice Cream Flavors

### ISSUE THREAD

**Issue by adityakalburgi** [DharshiBalasubramaniyam/ice-cream-parlour-website#156]
Hi!! @DharshiBalasubramaniyam  I would like to enhance the user experience by adding a dedicated FAQ section on our website that provides information about the No of flavors of ice cream we offer. This will help customers quickly find answers to common questions and increase engagement.

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.
