### ISSUE TITLE
creating a register button

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [DharshiBalasubramaniyam/ice-cream-parlour-website#158]
<img width="461" alt="Screenshot 2024-10-05 at 6 55 48 PM" src="https://github.com/user-attachments/assets/994ae767-9d9a-46d6-8b06-090a2988fc58">

similar to the login page , we can create a register/signup page.

**Comment by DharshiBalasubramaniyam** [comment]
Already done!
