### ISSUE TITLE
Improving font of home page

### ISSUE THREAD

**Issue by shreya20v** [DharshiBalasubramaniyam/ice-cream-parlour-website#162]
![image](https://github.com/user-attachments/assets/b0e593b2-da1e-4214-8fe3-e49623003c15)
This font should be changed because it makes the front page look messy. Also, it doesn't match and is not in sync with all the other fonts used on the home page.  I would like to work on this issue @DharshiBalasubramaniyam Please assign me this issue.

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by Dipanita45** [comment]
I would like  to work on the issue. Please assign it to me.

**Comment by Sahoobarsharani** [comment]
I would also like to work on this issue
