### ISSUE TITLE
adding a responsive search bar.

### ISSUE THREAD

**Issue by sayanp607** [DharshiBalasubramaniyam/ice-cream-parlour-website#163]
![Screenshot 2024-10-05 211326](https://github.com/user-attachments/assets/0e7ee117-b404-4bef-ad9c-b2de2895eb5e)
in the header portion, add a search bar which will show the exact result as per the input given by user.Please assign this task to me.

**Comment by hkpatel321** [comment]
I would like to contribute  and fix that
