### ISSUE TITLE
Adding a new category in the products.

### ISSUE THREAD

**Issue by shreya20v** [DharshiBalasubramaniyam/ice-cream-parlour-website#164]
We can add a Favourites category to the product page. This category will have one/ two flavors from each of the five categories. For example, the flavor of frozen yogurt strawberry can be a favorite (as it has been given great reviews). This will help new customers to try flavours that people prefer. I would like to work on it. Please assign me this issue. @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
