### ISSUE TITLE
[GSSOC-EXTND] Add code of conduct

### ISSUE THREAD

**Issue by subin-shk** [DharshiBalasubramaniyam/ice-cream-parlour-website#165]
A Code of Conduct is essential for establishing a positive and welcoming environment for all contributors and users of this project. It helps clarify the expectations for behavior within the community and addresses potential issues related to diversity, harassment, and misconduct.

I propose that a Code of Conduct be added to this repository in order to:

- Promote inclusivity and respect among contributors and users.
- Define unacceptable behavior and establish guidelines for reporting and resolving conflicts.
- Provide a point of reference for maintaining a healthy and safe community space.

Please assign this task to me.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
can you please add gssoc-ext label

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
