### ISSUE TITLE
User Reward and Review Section for IcyCo and Optimize font size and typography for better readability.

### ISSUE THREAD

**Issue by devki412** [DharshiBalasubramaniyam/ice-cream-parlour-website#167]
-Implement a rewards program for frequent customers at IcyCo, offering points or rewards  for purchases that can be redeemed for discounts and exclusive products.
-Adjust Landing Page Fonts: Optimize font size and typography for better readability.
-Expand Ice Cream Options: Add more varieties with detailed listings, including restaurant names.
-Revamp Color Scheme: Update colors for better contrast and modern aesthetics.
@DharshiBalasubramaniyam plz assign me this issue i want to work on it.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
