### ISSUE TITLE
"Newsletter Email Section Lacks Validation"

### ISSUE THREAD

**Issue by Kashish-Bhargava** [DharshiBalasubramaniyam/ice-cream-parlour-website#169]
![Screenshot 2024-10-05 215743](https://github.com/user-attachments/assets/682fe281-a4bd-4a98-abbc-d007285d144c)
Issue
The email input field in the newsletter subscription section does not have proper validation. Users can submit the form with an invalid email format, such as missing '@' or domain name, leading to unsuccessful subscriptions or incorrect data handling.
Solution
The system should validate the email format and show an error message for invalid emails, preventing the form from submitting until a valid email is entered.

Implement front-end email validation using HTML5's `input type="email"` or JavaScript to ensure proper email format before allowing submission.
Kindly assign me this issue and the labels GSSOCEXTD  and hactoberfest-accepted

**Comment by DharshiBalasubramaniyam** [comment]
Already assigned
