### ISSUE TITLE
Issue: Dark Mode UI Visibility and Mode Switching

### ISSUE THREAD

**Issue by Swarali1107** [DharshiBalasubramaniyam/ice-cream-parlour-website#17]
![pic1](https://github.com/user-attachments/assets/3c224901-56cd-448b-a3ce-bff532225737)
![pic2](https://github.com/user-attachments/assets/d1c668eb-4878-46a9-8bf4-bf1678f80ac9)
Description:
The UI of the website does not display properly in Dark Mode. Some elements, such as text and buttons, become hard to see or invisible due to the current color scheme. Additionally, there is no option to switch between Dark Mode and Light Mode, which limits accessibility and usability for users who prefer one mode over the other.

**Comment by Swarali1107** [comment]
can you please assign me this task

**Comment by DharshiBalasubramaniyam** [comment]
Not needed
