### ISSUE TITLE
Build Your Own Sundae Feature

### ISSUE THREAD

**Issue by yeshwanth-ds** [DharshiBalasubramaniyam/ice-cream-parlour-website#173]
# 🍨 Build Your Own Sundae Feature

This feature allows users to create their own custom sundaes by selecting base flavors, toppings, and sauces. Users can see a live preview of their sundae and the total price, which updates dynamically as they make their selections. Once satisfied, they can add the custom sundae to their cart for checkout.

## 🚀 Overview

The **Build Your Own Sundae** feature is designed to make the ice cream shopping experience more interactive and enjoyable. By providing users with customization options for their sundaes, this feature encourages creativity and personalization. Users can experiment with different combinations of base flavors, toppings, and sauces while viewing the price and preview in real-time.

## ⚙️ Tech Stack

- **HTML**: Provides the structure of the form used for selecting ingredients (base flavor, toppings, sauces) and displaying the live preview.
- **CSS**: Styles the form, preview section, and ensures the layout is responsive across different screen sizes.
- **JavaScript**: Handles dynamic functionality such as updating the live preview, calculating the total price based on the user’s selections, and managing the form interactions.

### 🍦 Base Flavor Selection
- Users can choose one or more base ice cream flavors (e.g., vanilla, chocolate, strawberry).

### 🍫 Toppings Selection
- Offers a range of toppings such as sprinkles, nuts, fruits, and candies.

### 🍯 Sauce Selection
- Choose from a variety of sauces like chocolate syrup, caramel, or strawberry sauce.

### 🔍 Live Sundae Preview
- As users customize their sundae, a visual preview of their creation is updated in real-time. This helps users visualize their choices before finalizing their selection.

### 💲 Dynamic Price Calculation
- The price of the sundae is automatically updated based on the user’s selected ingredients. Each ingredient (flavors, toppings, sauces) has a set price that contributes to the total.

### 🛒 Add to Cart
- Once the sundae is customized, users can easily add their creation to the shopping cart.

### ♻️ Clear All/Reset Option
- A reset button allows users to clear all selections and start over with a fresh sundae.

## 🛠️ How It Works

1. **HTML Form**: 
   - A form is provided where users can select a base flavor, toppings, and sauces via drop-down menus and checkboxes.
   
2. **CSS Styling**: 
   - The form and the preview section are styled with CSS to ensure a smooth, responsive experience on all devices.
   
3. **JavaScript Functionality**:
   - **Live Preview**: JavaScript captures user selections and dynamically updates the sundae preview.
   - **Dynamic Pricing**: Each ingredient has a set price, and JavaScript updates the total cost as the user selects different options.
   - **Add to Cart**: A button is provided for users to add their custom sundae to the shopping cart.

## 🎨 Theme Consistency

I will also make sure that the theme of this page matches with the main page theme. 

Since there is a lot of work, I would appreciate having a level 2 or level 3 tag. 

I would like you to assign me this task under the **gssoc-ext** tag.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
