### ISSUE TITLE
Adding FAQ's section in the nav bar

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [DharshiBalasubramaniyam/ice-cream-parlour-website#174]
i will add FAQ'S section in the nav bar to help in better responsiveness of the website
please assign me with the required labels as per gssoc'24 extended program

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
