### ISSUE TITLE
Creating the login and sign up page.

### ISSUE THREAD

**Issue by usha-here** [DharshiBalasubramaniyam/ice-cream-parlour-website#175]
Good evening, @DharshiBalasubramaniyam 
I saw that there is no sign up and login page for the site. So if you could please assign this issue to me with gssoc and hacktoberfest label , It would be really helpful.
Thank you.
![image](https://github.com/user-attachments/assets/1e8bbd75-f38d-430c-8b25-cce58fd929b2)

**Comment by usha-here** [comment]
@DharshiBalasubramaniyam  So should I work on this issue or not?

**Comment by iamprathama** [comment]
So should I work on this issue or not?

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
