### ISSUE TITLE
No sign up / Login Page 

### ISSUE THREAD

**Issue by pallaviii21** [DharshiBalasubramaniyam/ice-cream-parlour-website#179]
Add a signup and login for user .
That make a individual userprofile for user and user can easily access their orders and interest according to profile .

**Comment by pallaviii21** [comment]
Hey @DharshiBalasubramaniyam assign this issue i can fix it easily in minimum time and in a better way

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
