### ISSUE TITLE
Enhance Contact Form UI and adding functionality to Contact form

### ISSUE THREAD

**Issue by AkankshaSinghK** [DharshiBalasubramaniyam/ice-cream-parlour-website#18]
I am looking to enhance the UI of a contact form and add functionality to send messages via email. However, I am facing an issue where the email input displays 'invalid email format' even when a valid email is entered. 

Kindly assign this issue to me.
![Screenshot 2024-10-01 222302](https://github.com/user-attachments/assets/3573b3ef-6063-4d1b-871c-ae9f9ae65337)

**Comment by ArpitaAgrahari** [comment]
I am looking forward working on this issue. Please assign it to me.

**Comment by DharshiBalasubramaniyam** [comment]
> I am looking forward working on this issue. Please assign it to me.

Hi @AkankshaSinghK, thank you for creating this issue. You can improve the ui and check the trouble with the email format. For the functionality, can you please explain how will you do that?

**Comment by AkankshaSinghK** [comment]
@DharshiBalasubramaniyam

This is my approach: 

1.Improving the UI:

I'll update the layout to ensure it's more responsive and user-friendly by using proper spacing and padding between the form fields.
I'll add custom styling for focus and hover states to enhance user interaction, making it visually clearer when fields are being interacted with.
I'll also make sure error messages are displayed clearly, with invalid fields highlighted appropriately, so the user can quickly see where they need to make corrections.

2. Email Validation:

For the email format validation, I will use a regular expression (regex) to ensure that only valid email formats are accepted. The regex I'll use will be: /^[^\s@]+@[^\s@]+\.[^\s@]+$/. This will catch common errors like missing "@" or domain parts.

3.Adding Email Functionality:

For sending the form data via email, I plan to implement Mailin.js. This will allow us to send emails using an API key. When the form is submitted, it will first validate the email using the regex. If valid, the data will be sent via Mailin.js using an email template. I'll ensure the form captures the user's name, email, and message, and passes them to Mailin.js for email delivery.

**Comment by AkankshaSinghK** [comment]
@DharshiBalasubramaniyam Please add gssoc levels and hactoberfest levels to this issue
