### ISSUE TITLE
Add contributer.md file

### ISSUE THREAD

**Issue by Amulya-B28** [DharshiBalasubramaniyam/ice-cream-parlour-website#181]
I would like to add this file because it is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. Please assign this task to me.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
Can you please add gssoc-ext label

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!

**Comment by Amulya-B28** [comment]
Shall i create a contributors file or is it not needed?
