### ISSUE TITLE
Top review slider auto-slide behavior

### ISSUE THREAD

**Issue by saadgibawa** [DharshiBalasubramaniyam/ice-cream-parlour-website#182]
The top reviews section of the website has a slider displaying multiple reviews. When clicking on the navigation dots to view a specific review, the slider briefly shows the desired review but then automatically shifts to the next slide immediately. This makes it difficult for users to focus on the review they specifically selected. I want to work on this so please assign me this issue

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
