### ISSUE TITLE
[BUG] in contact us  page numeric validation, where the form restricts inputs to numeric values only

### ISSUE THREAD

**Issue by anish013326** [DharshiBalasubramaniyam/ice-cream-parlour-website#183]
#### it would be referred to as numeric validation, where the form restricts inputs to numeric values only.

![image](https://github.com/user-attachments/assets/c9312280-598c-492b-a9f8-bfab272ff2a2)

**Comment by rajveeerr** [comment]
I would like to work on this, please assign this to me

**Comment by DharshiBalasubramaniyam** [comment]
Solved
