### ISSUE TITLE
Hover Effects for Cart and User Icons

### ISSUE THREAD

**Issue by Renu1418** [DharshiBalasubramaniyam/ice-cream-parlour-website#185]
@DharshiBalasubramaniyam  I would like to take on the task of enhancing the hover effects for the cart and user icons. The existing hover effects already include color changes. My proposal is to improve these effects by adding scale transformations and smooth transitions to enhance user interaction.

Please assign this task to me.

**Comment by Renu1418** [comment]
@DharshiBalasubramaniyam please assign this task to me.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
