### ISSUE TITLE
Add Login and signup form under the profile icon

### ISSUE THREAD

**Issue by Mahima-2404** [DharshiBalasubramaniyam/ice-cream-parlour-website#186]
Add a dropdown section under the profile icon .This dropdown section will have the links to the login and signup page. These pages will have a well animated login and signup form.

**Comment by Mahima-2404** [comment]
@DharshiBalasubramaniyam Please assign me this issue. I am well capable

**Comment by DharshiBalasubramaniyam** [comment]
Solved
