### ISSUE TITLE
[Enhancement] : Enhancing the UI of 'delivery.html' page

### ISSUE THREAD

**Issue by rishu6263** [DharshiBalasubramaniyam/ice-cream-parlour-website#189]
The current "delivery.html" form lacks modern UI and user-friendly features. To improve the user experience, I propose adding the following enhancements:
  Floating Labels: Implement floating labels for a cleaner and more interactive form design.
  Responsive Layout: Improve mobile responsiveness using CSS Grid/Flexbox to optimize form display on smaller screens.
  Interactive Buttons: Add hover effects and animation to "Submit" and "Reset" buttons for better engagement.
  Progressive Disclosure: Break the form into multiple steps (e.g., Personal Info, Address Info) for a less overwhelming user experience.

Expected Outcome:
These changes will make the form more user-friendly, responsive, and visually appealing, enhancing the overall experience for users placing delivery orders.

**Comment by rishu6263** [comment]
Please do assign me this issue.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
