### ISSUE TITLE
create a following web page for enter your address section

### ISSUE THREAD

**Issue by ParulPrashar** [DharshiBalasubramaniyam/ice-cream-parlour-website#19]
We need to go beyond just one one web page so i want to add a page following enter your address where customer can enter their details like name, email, contact number, and finally address to be stored for future deliveries.

Kindly assign this issue to me with labels of hacktoberfest and gssoc @DharshiBalasubramaniyam

**Comment by ParulPrashar** [comment]
Thank you Mam.trying my best make an amazing contribution @DharshiBalasubramaniyam

**Comment by rutikakengal** [comment]
Create a Contact us page for contacting us and by using their email, name , mobile no , their message for contacting us . I would like to work on this
