### ISSUE TITLE
[Feature] Give a new look to the website.

### ISSUE THREAD

**Issue by pranusri1903** [DharshiBalasubramaniyam/ice-cream-parlour-website#197]
**Enhancement of the web pages**
The website given is good on its own but the colour palette is not that cool.
Also the font colour and the background colour in the footer is hard to distinguish.
And some more upgrades regarding the glow effect etc.

**Additional context**
Adding a few more animation to the products to make it more eye catchy,
Make forms look better
Align the divs so that there minimum empty space left on the sides.

**Comment by DharshiBalasubramaniyam** [comment]
Not needed!
