### ISSUE TITLE
Add bottom to top button

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#2]

**Comment by mrvishalsharma01** [comment]
can i work on this issue please assign me this question

**Comment by SanikaBhalerao1345** [comment]
hi @DharshiBalasubramaniyam i would like to work on this issue

**Comment by Anushka184** [comment]
Pls assign me with this task @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
@mrvishalsharma01 the issue is assigned to you. All the best.

**Comment by mrvishalsharma01** [comment]
Thank you i am working in this issue

**Comment by mrvishalsharma01** [comment]
https://github.com/user-attachments/assets/ea0cd791-6518-4d02-a09e-7fafdac9f794

I have completed my task can i send you pull request? or do i need to change something

**Comment by DharshiBalasubramaniyam** [comment]
> ice-cream.mp4 
> I have completed my task can i send you pull request? or do i need to change something

Sure

**Comment by RanitDERIA** [comment]
I'd love to be assigned to issue #79   as I have the relevant experience in Web Dev and believe I can provide an efficient solution. Looking forward to contributing!
