### ISSUE TITLE
Add Login Page Functionality for User Authentication

### ISSUE THREAD

**Issue by T-Fathima** [DharshiBalasubramaniyam/ice-cream-parlour-website#205]
**Issue Description:**
**Feature Request:** I would like to propose adding a login page to the website for better user experience and security. This feature will enable users to create accounts and securely log in to manage personalized content, such as saving favorites or tracking orders.

I would like to work on this issue.
Please assign it to me under gssoc-ext'24.

**Comment by eshalshaikh07** [comment]
Adding of login feature with signup functionality along with a firebase for storing data of user in database of firebase.
Along with styling that match the theme and makes it more aesthetic, I would like to work on this!
