### ISSUE TITLE
Increase logo size

### ISSUE THREAD

**Issue by ParulPrashar** [DharshiBalasubramaniyam/ice-cream-parlour-website#21]
the logo is very small almost next to not recognisable in nav bar. It would be better if we enhance its size

**Comment by ParulPrashar** [comment]
@DharshiBalasubramaniyam kindly assign this issue to me.
labels mention gssoc, hacktoberfest

**Comment by clownfish1805** [comment]
@DharshiBalasubramaniyam I would like to work on this issue. Please assign me under GSSOC'24 extended

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue. Please assign me under GSSOC'24 extended
