### ISSUE TITLE
[ Enhancement ] Update State Input Field to Dropdown Select Menu

### ISSUE THREAD

**Issue by akash70629** [DharshiBalasubramaniyam/ice-cream-parlour-website#217]
**Description:**

Currently, the _**State**_ input field allows users to enter any text. To improve data accuracy, replace the text input with a dropdown select menu containing all Indian states.

**Affected Page:**  _delivery.html_ , _catering.html_

Labels: Feature, Enhancement, UI/UX, Data Validation

**Comment by T-Fathima** [comment]
I would like to work on it. 
Please assign me this
