### ISSUE TITLE
Checkout Button Not Functional

### ISSUE THREAD

**Issue by subin-shk** [DharshiBalasubramaniyam/ice-cream-parlour-website#219]
Title: Checkout Button Not Functional

Description: The checkout button on the website is currently not working. Clicking the button does not redirect the user to the payment or checkout page, and no actions are triggered. This is a critical issue affecting the e-commerce functionality of the site.

Steps to Reproduce:

Add items to the cart.
Click on the checkout button.
Observe that no action is taken or no page is loaded.
Expected Behavior: The checkout button should redirect the user to the checkout page or initiate the checkout process.

Proposed Solution: I'd like to work on this issue by investigating the button functionality and fixing the redirection or missing action.

Priority: High

Screenshot:

https://github.com/user-attachments/assets/8d634979-9594-4fc6-9a1d-b15a56dc17fa

**Comment by T-Fathima** [comment]
I would like to work on this and fix the issue 
Please assign it to me under gssoc-ext'24.

**Comment by subin-shk** [comment]
hello. im the one who raised the issue so assign it to me please

**Comment by subin-shk** [comment]
m

**Comment by subin-shk** [comment]
ugly bitch
