### ISSUE TITLE
Implement a "Wishlist" Feature

### ISSUE THREAD

**Issue by ArpitaAgrahari** [DharshiBalasubramaniyam/ice-cream-parlour-website#22]
Allow users to add their favorite ice cream items to a Wishlist for easy access later. This feature should include functionalities to add items to the Wishlist, view the Wishlist, and remove items from the Wishlist. Please allow it to me.

**Comment by akdwivedi-explorer** [comment]
Please assign this to me under "Hacktoberfest". I will add this feature.
