### ISSUE TITLE
Date picker in catering form

### ISSUE THREAD

**Issue by shalini-bhandari** [DharshiBalasubramaniyam/ice-cream-parlour-website#224]
should limit the minimum date in the form as today's date
<img width="771" alt="Screenshot 2024-10-06 at 17 56 48" src="https://github.com/user-attachments/assets/2340e8c1-dcd3-4886-b833-70865863e823">

@DharshiBalasubramaniyam Kindly assign me under gssoc-ext and hacktoberfest-accepted with appropriate level.
Regards

**Comment by Mahateaa** [comment]
hey @DharshiBalasubramaniyam  can you please assign this to me?
