### ISSUE TITLE
 Add Functionality to Increment and Decrement Items in Cart

### ISSUE THREAD

**Issue by 2004vivek** [DharshiBalasubramaniyam/ice-cream-parlour-website#231]
I need to implement functionality to increment and decrement the quantity of individual items in the cart. This will allow users to easily adjust item quantities without having to re-add or remove items from the cart entirely.

![image](https://github.com/user-attachments/assets/0a4799f4-99bc-4a74-87b7-3974b3078a5d)

**Comment by Pallavi-Mukalla** [comment]
@DharshiBalasubramaniyam  please assign me this issue . I am confident that i will be able to rectify this
