### ISSUE TITLE
Color of Icon Home is different 

### ISSUE THREAD

**Issue by Anjalis14** [DharshiBalasubramaniyam/ice-cream-parlour-website#232]
Color of the Home icon in navbar is different that does'nt match the current website .
![image](https://github.com/user-attachments/assets/86714d17-7288-4fef-8719-c9d3d6f02f86)
I will fix that issue and will add good looking color to that

**Comment by Anjalis14** [comment]
@DharshiBalasubramaniyam plz assign me this isssue i will fix it in a while

**Comment by pameladeysarkar2003** [comment]
please assign me with this issue @DharshiBalasubramaniyam
