### ISSUE TITLE
Add a dedicated product page!

### ISSUE THREAD

**Issue by Hustler004** [DharshiBalasubramaniyam/ice-cream-parlour-website#233]
It is better to show some featured products on the home page but considering the scalability of your project, we should add a product page differently to handle all the products.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Hustler004, I am assigning you the issue. Kindly make sure that add to cart functionality is working. 

🔴🔴🔴 Kindly don't remove the products section from index.html. because other contributors are also working on that section. I'll remove it later.

**Comment by Hustler004** [comment]
Okk sure! I'll get started asap
