### ISSUE TITLE
Login Credentials : Adding backend for login and logout

### ISSUE THREAD

**Issue by Chandan-Kr-dev** [DharshiBalasubramaniyam/ice-cream-parlour-website#237]
I want to make the login System by integrating backend with encrypted passwords to keep the track of the user and show his profile on the navbar . Any time any user visits the website will login and his profile will be shown up

**Comment by DharshiBalasubramaniyam** [comment]
Which technology will you use?

**Comment by Chandan-Kr-dev** [comment]
I will be using Express js and mongoDB for the backend and bcrypt js for encryption of password
