### ISSUE TITLE
Next/Previous arrow icon missing

### ISSUE THREAD

**Issue by tanishkagarg1911** [DharshiBalasubramaniyam/ice-cream-parlour-website#24]
Adding a next arrow icon would look great in the " Top Reviews " section..it would make easier to go from one review to another and make up a good user experience 

 @DharshiBalasubramaniyam   kindly assign this issue to me.
labels mention gssoc-ext  hacktoberfest

**Comment by tanishkagarg1911** [comment]
Sir @DharshiBalasubramaniyam kindly assign this issue to me.
I am new to open source contributions but have strong command over frontend development

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam kindly assign this issue to me. I am new to open source contributions but have strong command over frontend development

Hi @ParulPrashar, thank you for creating the issue. The issue is assigned to you. All the best.

**Comment by tanishkagarg1911** [comment]
Thankyou @DharshiBalasubramaniyam mam, I am working on the issue !

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue , as I have a strong background in CSS and HTML. Please assign me under GSSOC'24 extended
