### ISSUE TITLE
add contributing.md file 

### ISSUE THREAD

**Issue by INam1995** [DharshiBalasubramaniyam/ice-cream-parlour-website#240]
Hey @DharshiBalasubramaniyam 
I would like to request to be assigned the issue for adding a CONTRIBUTING.md file to this project. This file will provide clear guidelines for potential contributors, enhancing our community's onboarding experience and encouraging more participation.

Here’s a brief overview of what I plan to include in the CONTRIBUTING.md file:

Project Overview
Getting Started instructions
Contributing Guidelines
Implementation steps for the search functionality enhancement
Acknowledgment of the project's Code of Conduct

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
and add the gssoc-ext label
