### ISSUE TITLE
Add to Wishlist Icon , Imrpoved FAQ, Title of Login and Sign Up page

### ISSUE THREAD

**Issue by Harshitha-Annam** [DharshiBalasubramaniyam/ice-cream-parlour-website#245]
---> when we click on Login icon in navbar it takes us to Login Page but the title of the Page Shows Floating Label Icon. Its the same with 
        Sign in Page.

---->Can add 'Add to Wishlist/Save'  Icon for products and 'Wishlist/Saved'  icon  in navbar.
----> Can add smoother transitions in FAQ Section. 
Could you please assign this to me ?

- [x] I am a GSSOC Extd contributor.

**Comment by DharshiBalasubramaniyam** [comment]
First one okay. But 2nd and 3rd not needed
