### ISSUE TITLE
add mini chattbot to the website

### ISSUE THREAD

**Issue by rutikakengal** [DharshiBalasubramaniyam/ice-cream-parlour-website#248]
This chatbot gives quike response to the users questions and answers all questions of users, assiggn me @DharshiBalasubramaniyam  i like to work on it Add gssoc-ext,hactoberfast accepted and level labels to the issue

**Comment by pameladeysarkar2003** [comment]
please assign me with the task i'm confident about fixing the issue @DharshiBalasubramaniyam
