### ISSUE TITLE
Add new social media icon 

### ISSUE THREAD

**Issue by Antima2004** [DharshiBalasubramaniyam/ice-cream-parlour-website#249]
In the footer section there are social media but the twitter the most famous social media is not there in your website footer
Here's the image of it:
![Screenshot_2024-10-07-15-42-55-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/4a23c52f-711e-48c2-b5d0-91da1d531614)
Please assign this to me and also add label to this issue

**Comment by sunidhi3** [comment]
Hey I'm Gssoc contributor so please assign me the issue..

**Comment by sunidhi3** [comment]
Hey I'm Gssoc contributor so please assign me the issue..

**Comment by Antima2004** [comment]
Thanks
