### ISSUE TITLE
correcting the locations in footer (showing same location four times) can you add GSSOC 24 ext label to this 

### ISSUE THREAD

**Issue by devxMani** [DharshiBalasubramaniyam/ice-cream-parlour-website#25]
![image](https://github.com/user-attachments/assets/48919bf5-2677-411e-83b3-e2f8f861ff50)

**Comment by devxMani** [comment]
assign this task to me .............................

**Comment by DharshiBalasubramaniyam** [comment]
Hi @devxMani , thank you for creating the issue. The issue is assigned to you. All the best.

**Comment by rounakdey6** [comment]
can you assign this me ? I really want to work on this project
