### ISSUE TITLE
Unresponsive Login page on mobile phones

### ISSUE THREAD

**Issue by ParulPrashar** [DharshiBalasubramaniyam/ice-cream-parlour-website#253]
The login page is not at all responsive for mobile. Moreover even in desktop the box does not fit all contents leading to untidy look.
the reference images are below.
@DharshiBalasubramaniyam kindly assign this issue to me with label of gssoc and hacktoberfest
![Screenshot (23)](https://github.com/user-attachments/assets/e037841d-9f90-4270-b909-469ac6ff7bdf)
![Screenshot (24)](https://github.com/user-attachments/assets/943188b7-1530-495f-864e-0c72dea28d34)

**Comment by Mansi07sharma** [comment]
Hii, It is great issue , Kindly assign it to me I would like to work on that and add some labels.
