### ISSUE TITLE
hover to div needed

### ISSUE THREAD

**Issue by Amankr200** [DharshiBalasubramaniyam/ice-cream-parlour-website#256]
without hover this page in not looking responsive for user @DharshiBalasubramaniyam 

https://github.com/user-attachments/assets/922f24af-2624-49b8-aa04-b1174bcad7ba

**Comment by anshusaini19** [comment]
i would really like to make resolve this issue. please assign it to me

**Comment by Amankr200** [comment]
pls assign me as i have raised it first @DharshiBalasubramaniyam
