### ISSUE TITLE
Add search bar in nav Ul Item

### ISSUE THREAD

**Issue by Anjalee01** [DharshiBalasubramaniyam/ice-cream-parlour-website#258]
There is no search bar in header I want to add it

@DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Anjalee01 , Can you do it similar to geeksfor geeks website. The dropdown is not needed. Just the input box

**Comment by Anjalee01** [comment]
@DharshiBalasubramaniyam  Yes I can Please assign me this task.

**Comment by Anjalee01** [comment]
@DharshiBalasubramaniyam please respond.
