### ISSUE TITLE
unorganized layout of sign up page

### ISSUE THREAD

**Issue by sauraabhh** [DharshiBalasubramaniyam/ice-cream-parlour-website#263]
the problems are :-
1. it is not fit to page 
2. layout is unattractive
3. icons are un organized
![Screenshot 2024-10-07 190740](https://github.com/user-attachments/assets/98784dd0-712b-43fd-819d-ec8977139f29)

**Comment by sauraabhh** [comment]
@DharshiBalasubramaniyam please assign me this under GSSOC'24 ext

**Comment by Pallavi-Mukalla** [comment]
@DharshiBalasubramaniyam please assign me this under GSSOC'24 ext
