### ISSUE TITLE
Revamping the Navbar: Contributing to an Open-Source Project for a Sleek and Modern Design

### ISSUE THREAD

**Issue by khurshed07** [DharshiBalasubramaniyam/ice-cream-parlour-website#266]
*****************************************************Before Changes************************************************************************
![Screenshot 2024-10-07 220139](https://github.com/user-attachments/assets/4cda6a10-f06a-4897-a4d1-e6e1d5a73205)

*****************************************************After Changes*************************************************************************
![Screenshot 2024-10-07 215719](https://github.com/user-attachments/assets/fff4b132-1d44-40d8-abb5-904e5577756e)
![Screenshot 2024-10-07 215732](https://github.com/user-attachments/assets/f5ba09c9-b6bc-4e2e-b6aa-7fa2a08b85ea)
![Screenshot 2024-10-07 215740](https://github.com/user-attachments/assets/aa70685f-6c8d-41bb-873c-722d34cb1f89)
![Screenshot 2024-10-07 215748](https://github.com/user-attachments/assets/18d37365-b34e-41de-b9d0-10215f6dd05b)
![Screenshot 2024-10-07 215758](https://github.com/user-attachments/assets/a27bd0b8-9130-42d0-a1e9-36836240610b)
![Screenshot 2024-10-07 215810](https://github.com/user-attachments/assets/0d83d5a7-f582-4012-877e-95885da23b73)

Hi @DharshiBalasubramaniyam

I recently updated the navbar for your project to make it more attractive and user-friendly. I've attached screenshots of the changes, and I'd love to contribute to this enhancement to improve the overall design.

Please assign me to this task. It would be a great opportunity for me to contribute while enhancing my skills.

Looking forward to your response!

Best regards,
Khurshed07
GitHub: https://github.com/khurshed07

**Comment by khurshed07** [comment]
Hi @DharshiBalasubramaniyam
Please assign this issue #266 to me for contribution

**Comment by khurshed07** [comment]
Hi @DharshiBalasubramaniyam
Please assign this issue #266 to me for contribution

**Comment by DharshiBalasubramaniyam** [comment]
Please use the styles for only active link. leave other as default

**Comment by khurshed07** [comment]
Okay
