### ISSUE TITLE
Change Compressed Fonts for Better Readability

### ISSUE THREAD

**Issue by Mehtarishita** [DharshiBalasubramaniyam/ice-cream-parlour-website#28]
I’ve noticed that the current font on the website appears a bit compressed, which can make reading challenging. However, I love the overall design and think a few enhancements could significantly improve readability and user engagement. With some adjustments, we can make the site even more eye-catching and accessible for all users!
![image](https://github.com/user-attachments/assets/8de3e793-cbbf-44b4-8a08-c754e2d8786d)
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Mehtarishita , thank you for creating the issue. I would like to change only the fonts and the colors, not entire ui. Can you do that? You can update existing root variables for colors and create new root variables for fonts.

**Comment by Mehtarishita** [comment]
Sure ,I can do that 
Kindly assign this.

**Comment by Kavish-Paraswar** [comment]
Please assign this issue to me under ... gssoc 2024 extended

**Comment by DharshiBalasubramaniyam** [comment]
> Sure ,I can do that Kindly assign this.

Sorry for late. Now only I noticed your reply. Assigning to you
