### ISSUE TITLE
Add hovering effect

### ISSUE THREAD

**Issue by FSBM** [DharshiBalasubramaniyam/ice-cream-parlour-website#285]
![image](https://github.com/user-attachments/assets/45c91ad3-936a-42e5-be46-da335225506e)

While hovering over the cards, I can be popped up using transform.It'll make the user experience better.
Assign me this task and if it's possible ,please assign me this task under hacktoberfest.

**Comment by Sakshi2048** [comment]
@DharshiBalasubramaniyam do assign this issue to me

**Comment by Akanshaku** [comment]
I would like to work on this please assign me this issue @DharshiBalasubramaniyam

**Comment by Sakshi2048** [comment]
I'm not the owner.
Do contact to the owner.
