### ISSUE TITLE
Regarding issue assignment

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#29]
Dear contributors,
Kindly note that the issues will be assign based on the first in first out method. Hence try to create your own issues. All the best!

**Comment by satyam1024** [comment]
Hi DharshiBalasubramaniyam,

I hope you're doing well! I’ve created issue #15. When you get a chance, could you please review it and assign it under GSSOC and Hacktoberfest?

Thank you so much!

**Comment by Anujyadav0074** [comment]
please assign me issue #303 i have create this issue and i even have resolver it just sending pull request is remaining and could you also assign this under gssoc and hacktoberfest 

thank you

**Comment by Anujyadav0074** [comment]
Please assign me #303

**Comment by Anujyadav0074** [comment]
Please assign me issue #362 i hve created this issue and please add tags like. Gssoc hactoberfest
