### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [DharshiBalasubramaniyam/ice-cream-parlour-website#296]
I would like to request the addition of a dark theme to the website. A dark theme would enhance the user experience, especially for users who prefer low-light environments or have accessibility needs.  Adding a dark theme improves readability in low-light conditions.

@DharshiBalasubramaniyam please assign me this task

**Comment by Yashwanth112004** [comment]
I have worked with HTML, CSS and JavaScript. I would like to contribute to this task.
@DharshiBalasubramaniyam please assign me this task. It will be helpful for my growth also.
Best Regards,
Puligilla Yashwanth
Contributor
