### ISSUE TITLE
Nav links are not active

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#3]
Problem: Now `Home` link is active (In grey color) for all sections.

Solution: When a particular section is visible to user, the respective link should active (appear in grey color).  

Kindly update `nav.js` for implementing the solution.

**Comment by Web-Dev-Learner** [comment]
i'm ready to improve section can you assign the issue and add labels to this issue

**Comment by hannah-maria** [comment]
i would like to work on this, kindly assign me this issue

**Comment by unnati-078** [comment]
Hi, I hope you're doing well. I am a contributor for GirlScript Summer of Code Extended Edition and would love to work on this issue. Could you please assign it to me? Thank you!

**Comment by DharshiBalasubramaniyam** [comment]
@Web-Dev-Learner  the issue is assigned to you. All the best.

**Comment by Web-Dev-Learner** [comment]
Thank you for assigning me as a contributor to the Project. I'm excited to start contributing and help improve the project.

Best regards,
Shrinedhi.M.R

**Comment by Swarali1107** [comment]
i would like to work on this, kindly assign me this issue @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
> Thank you for assigning me as a contributor to the Project. I'm excited to start contributing and help improve the project.
> 
> Best regards, Shrinedhi.M.R

Any updates ?

**Comment by Antima2004** [comment]
please assign this to me
