### ISSUE TITLE
Add a responsive password strength meter during sign-up.

### ISSUE THREAD

**Issue by PavanTeja2005** [DharshiBalasubramaniyam/ice-cream-parlour-website#302]
I want to add a responsive password strength level meter which can display user's password strength when they are signing up.

It does.,
Display password strength to users as they create their passwords.
Improve user privacy by encouraging stronger passwords.
Enhance user experience with real-time feedback.

I'm working in gssoc extended. Please provide me suitable labels.

**Comment by icemberg** [comment]
Can you assign this issue to me . I would like to work on this issue

**Comment by DharshiBalasubramaniyam** [comment]
@PavanTeja2005, Are you there?

**Comment by PavanTeja2005** [comment]
Yes, I have found some bugs in the existing signup page. So I'm summarising and working on them. I will submit PR today.
