### ISSUE TITLE
We can implement a better hover color than pink.

### ISSUE THREAD

**Issue by shruti9935** [DharshiBalasubramaniyam/ice-cream-parlour-website#305]
Can you please assign me this task.
and can you please add gssoc ext

**Comment by vaibhavguptahere** [comment]
Assign this task to me I will sort it

**Comment by eshitatalukdar08** [comment]
Hello @shruti9935, I believe that making a change in the hover color with a contrasting shade will really enhance the appeal of our website. Additionally, incorporating some subtle animations would add a dynamic element. I also think it would be great to introduce a sliding hover effect in the navbar when switching between buttons. I'm genuinely excited about the prospect of working on this task and contributing to the project. Please assign me to this task

**Comment by shruti9935** [comment]
Hey @DharshiBalasubramaniyam,I was the first to raise this issue, so this work should be assigned to me.
