### ISSUE TITLE
Adding a home page button on Login and Signup page

### ISSUE THREAD

**Issue by Kcode15** [DharshiBalasubramaniyam/ice-cream-parlour-website#306]
Adding a home page button on the login and signup page to enhance the user experience

![image](https://github.com/user-attachments/assets/2f666c8e-82fb-4089-a898-786e5283de60)

![image](https://github.com/user-attachments/assets/000ab47a-d8aa-4896-b4d5-bdedaf00c326)

**Comment by ayushbhjh** [comment]
@Kcode15 I already work on navigation please assign this task to me

**Comment by Divyansh8843** [comment]
@Kcode15 I want to work on this issue . Sir please assign this issue to me.
