### ISSUE TITLE
Improve Content Layout on "About Us" Page

### ISSUE THREAD

**Issue by snehhhcodes** [DharshiBalasubramaniyam/ice-cream-parlour-website#308]
# Issue Description:

The current design of the "About Us" page prominently features a large image that occupies significant space. While visual elements are important, this layout may not fully engage our visitors and can create a cluttered experience.  As a result, visitors are less likely to engage with the written content, and the overall message is not effectively conveyed.

# Expected Behavior:

To enhance user engagement, we need to create a visually appealing design that captures attention and encourages visitors to read the content. A more balanced layout will not only optimize the use of space but also improve the overall user experience, making it easier for users to connect with our brand story.

I would like to take on this task to improve the "About Us" page. Please consider assigning this issue to me for further action.

**Comment by snehhhcodes** [comment]
@DharshiBalasubramaniyam hey there please review this issue once and if suitable assign it to me under approporiate gssoc and hactoberfest level!!

It would be great if you can assign this issue to me for level 2.
Thankyou

**Comment by DharshiBalasubramaniyam** [comment]
Hi @snehhhcodes, kindly make sure that the oage is responsive for mobile view. 

If possible share a sample ui before starting.

**Comment by snehhhcodes** [comment]
> Hi @snehhhcodes, kindly make sure that the oage is responsive for mobile view.
> 
> If possible share a sample ui before starting.

Surely, here are some!!
![Screenshot 2024-10-09 071251](https://github.com/user-attachments/assets/e8bdd18f-1dd3-4cfd-8591-8343ad936fa5)
![Screenshot 2024-10-09 071058](https://github.com/user-attachments/assets/79833d5c-893d-43a0-8eb1-36b119f5c74d)
i can do these with videos to make it more engaging and user friendly so that without even reading user can get to know about the objective of website

**Comment by vijaychandra1910** [comment]
Give it to me I want to work on it. @DharshiBalasubramaniyam
