### ISSUE TITLE
 Add Sign-In Page When Clicking on User Icon on Home Page

### ISSUE THREAD

**Issue by Vishwajeet594** [DharshiBalasubramaniyam/ice-cream-parlour-website#31]
### Description:
 **Currently, clicking on the User Icon on the home page does not trigger any action or redirection. The expected behavior is that clicking on the icon should take users to a Sign-In Page, allowing them to log into their account. This functionality needs to be added to improve user access to the sign-in feature.**

### Implement Sign-In Page Redirection:

**1. When the user clicks on the User Icon located on the home page, they should be redirected to the Sign-In Page.
2. The Sign-In Page should allow users to enter their Email/Username and Password to log in.**

### Sign-In Page Design:

**1. The Sign-In Page should follow the website’s design guidelines, including appropriate branding, colors, and fonts.
2. It should include a "Forgot Password" link and possibly a link to the Sign-Up Page for new users.
3. Add appropriate error handling for incorrect login credentials.**

**Comment by VaishnaviShinde5** [comment]
Please assign this to me under "GirlScript summer of code". I wil create this

**Comment by clownfish1805** [comment]
@DharshiBalasubramaniyam 
I would like to take up the task of implementing the User Icon click redirection to the Sign-In Page and the corresponding Sign-In Page design. 

**My plan is as follows:**

1. **Redirection:** I will ensure that clicking the User Icon on the home page redirects users to the Sign-In page.
2. **Sign-In Page Functionality:**
Users will be able to enter their **Email/Username and Password** to log in.
I'll include a "**Forgot Password**" link for user convenience and a link for new users to navigate to the Sign-Up page.
3. **Design Consistency**: I'll follow the **website's design guidelines** (branding, colors, fonts) to ensure a seamless user experience.
4. **Error Handling:** Proper error messages will be displayed for incorrect login credentials to enhance usability and security.
With this approach, I aim to complete the task efficiently, keeping the design and functionality aligned with the project's standards.

Please assign me this task under **GSSOC'24 extended** and with its level labels

**Comment by DharshiBalasubramaniyam** [comment]
@Vishwajeet594 can you follow below ui? 

![17280377173344460933455738617459](https://github.com/user-attachments/assets/858e25f2-815a-4a8c-8818-eb19154b3684)

Replace the gitlab logo with our logo

**Comment by Vishwajeet594** [comment]
ok i will do the same
