### ISSUE TITLE
fix Alignment of Text in middle in product section

### ISSUE THREAD

**Issue by AsifQamar** [DharshiBalasubramaniyam/ice-cream-parlour-website#310]
fixing alignment of text in middle for more visual appeal
<img width="960" alt="Screenshot_103" src="https://github.com/user-attachments/assets/deb0020f-fcc1-43ed-ab03-7420816523c6">

**Comment by AsifQamar** [comment]
@DharshiBalasubramaniyam please review this and tag it with Gssoc and hacktober

**Comment by DharshiBalasubramaniyam** [comment]
Sorry, I didnt get your issue point correctly.

**Comment by AsifQamar** [comment]
> Sorry, I didnt get your issue point correctly. Can you explain bit more..

yes , the names of the products like Greek Yogurt should be in middle , it will be more pleasing to see

**Comment by Khatwangadhareddy** [comment]
Assign it to me
