### ISSUE TITLE
navbar underline hover effect

### ISSUE THREAD

**Issue by Krishnamverma951** [DharshiBalasubramaniyam/ice-cream-parlour-website#313]
i have already use in website

please assign me 

https://github.com/user-attachments/assets/2d8bbc58-94c0-42e5-b24b-94d02a47a052

**Comment by ayushbhjh** [comment]
I want to work on this hover effect

**Comment by sunidhi3** [comment]
Hey I'm Gssoc contributor so please assign me the issue..
