### ISSUE TITLE
NOTICE ⚠️: Program Manager - GSSOC Extended

### ISSUE THREAD

**Issue by MastanSayyad** [DharshiBalasubramaniyam/ice-cream-parlour-website#318]
Hi @DharshiBalasubramaniyam,

I’ve noticed that there are several open issues in your repository that haven’t been assigned to contributors, along with multiple open PRs that are still pending review. Please take some time to:

- **Merge PRs** where the work is complete.
- **Assign issues** to contributors and make sure proper labels are added.

If you come across issues that are unnecessary or not something you plan to fix, kindly close them, as well as any PRs that were raised without an assigned issue. Keeping them open might lead to confusion or complaints from contributors who are waiting for assignment.

Thank you for your attention to this!

![image](https://github.com/user-attachments/assets/9013e00b-5dc9-4ccf-afac-5d2b80233679)
![image](https://github.com/user-attachments/assets/908f460c-1a25-46e3-87a8-dbe352e3b999)

Thank You
Program Manager 
GSSOC Extended

**Comment by DharshiBalasubramaniyam** [comment]
Hi @MastanSayyad, kindly check #274. I was in active until last Sunday. In weekdays I am quiet busy. I can clear everything on weekends only.


Is that a problem?

**Comment by MastanSayyad** [comment]
Hi @DharshiBalasubramaniyam 

Thank you for the update, and I understand your situation. I didn't notice that you had pinned the issue, but the contributors were raising complaints as many don't take the time to read the pinned information. I'll share that you already announced that you won't be available, did you contacted your mentors about this so that they can handle your repo when you're busy?

As you know, this program runs for just one month, and we now have only about 20 days left and we need active projects with active PA. I would kindly request if you could make some time to at least merge the open PRs. These PRs are crucial for contributors to receive their points and show up on the leaderboard.

Thank you again for your hard work!

Best regards,
Mastan - Program Manager,
GSSOC Extended
