### ISSUE TITLE
Flavors in the footer section not responsive

### ISSUE THREAD

**Issue by bm9240** [DharshiBalasubramaniyam/ice-cream-parlour-website#325]
Hello,
The Flavors in the footer section when clicked on scrolls back to start of the page.
Instead I would like to add on that when a particular flavour is selected the screen scrolls to our products and that particular flavor gets highlighted for 2-3 seconds.
Please assign me this Issue @DharshiBalasubramaniyam 
Thanks !!

**Comment by prisha-sh** [comment]
hey @Sarthakkashyapp i'd like to work on this issue, I'll be sharing the solution asap!
