### ISSUE TITLE
make Privacy policy link responsive

### ISSUE THREAD

**Issue by ShrishtiSingh26** [DharshiBalasubramaniyam/ice-cream-parlour-website#327]
I wish to make the privacy policy section responsive such that when a user clicks on it the privacy policies are visible to them. In this I will add content for the privacy terms as well

![image](https://github.com/user-attachments/assets/c4438302-a075-4994-9d47-baf29e966bd5)

I wish to contribute in this project....
hope you will assign me this issue under hacktoberfest and GSSOC -extd 
Thank you!

**Comment by DharshiBalasubramaniyam** [comment]
Hi @ShrishtiSingh26, you can create a new oage for this.
