### ISSUE TITLE
FEAT: Add the twitter link in the follow us 

### ISSUE THREAD

**Issue by itskundanhere** [DharshiBalasubramaniyam/ice-cream-parlour-website#338]
![Screenshot 2024-10-10 125047](https://github.com/user-attachments/assets/19a6775c-32e4-4e3c-bc50-1641ca9693f2)

In the IcyCo website, in the follow us section add the icon of the "Twitter".

**Comment by Rohit72099** [comment]
i want to work on this issue please assign this to me

**Comment by Rohit72099** [comment]
i have solve this issue
![updated](https://github.com/user-attachments/assets/99433c89-92ca-4e5c-a784-aeff3149ddd0)
