### ISSUE TITLE
Creating payment option for the cart objects with subtotal.

### ISSUE THREAD

**Issue by AnanyaSinha16** [DharshiBalasubramaniyam/ice-cream-parlour-website#343]
![image](https://github.com/user-attachments/assets/88ad5af7-1e0d-469d-b1ae-c9dc2a3dc3b2)
 After proceeding the subtotal there is no further option for payment or anything .I can fix that by connecting it to any online mode paying application.

**Comment by JOSHITHA6** [comment]
Please assign this task to me @DharshiBalasubramaniyam under gssoc'24 extd and hacktoberfest
