### ISSUE TITLE
FAQ popup model

### ISSUE THREAD

**Issue by meghanakn473** [DharshiBalasubramaniyam/ice-cream-parlour-website#345]
Adding faq model to the footer , just beside like bottom to scroll option.
so wen user clicks on it the faqs will be popped

it reduces spaces and improves ui

@DharshiBalasubramaniyam please assign me this issue under level 3, gssoc-extd, hacktoberfest

**Comment by DharshiBalasubramaniyam** [comment]
Can you show any screenshots or demos for your idea?

**Comment by meghanakn473** [comment]
> Can you show any screenshots or demos for your idea?


https://github.com/user-attachments/assets/06c6a2d8-9823-4b82-91fa-5576ead8ece1

smtg like this i wanted to implement
i hope ull consider it :)
please assign me this issue at level 3

**Comment by meghanakn473** [comment]
Okay I will do it

**Comment by DharshiBalasubramaniyam** [comment]
> Okay I will do it Please assign Also where shd I refer info for creating it?

cut that faq section from the index.html and put in a different file. add nav and footer

**Comment by meghanakn473** [comment]
@DharshiBalasubramaniyam done!! i hv made pr please check and allow merge!!
