### ISSUE TITLE
Issue: Proper formatting of login page must be done for better user experience

### ISSUE THREAD

**Issue by JOSHITHA6** [DharshiBalasubramaniyam/ice-cream-parlour-website#349]
I have observed that social media icons overflowed due to which salesforce option button coming out of the login form. I would like to re-adjust the size. 
Also, "Already have an account, sign in" seems to be very small due to which its not visible to the users.I want to fix this also.

Please assign this task to me @DharshiBalasubramaniyam under gssoc'24 extd and hacktoberfest

In the screenshot, it's clearly visible wherein the salesforce came out of the form which looks awkward

![Screenshot (174)](https://github.com/user-attachments/assets/a492bed0-6921-4d10-abe9-4b62eb0ad479)

**Comment by Rohit72099** [comment]
i have solved this issue
![image](https://github.com/user-attachments/assets/8a9e4ace-4e91-4789-83ca-d73daf82c74c)
