### ISSUE TITLE
Registration page and sign in page ui issue and heading

### ISSUE THREAD

**Issue by 17arindam** [DharshiBalasubramaniyam/ice-cream-parlour-website#360]
currently the registration page and sign in page's ui needs to be fixed . i want to fix those pages ui and want to clearly mention the purpose of the page in the heading 
![image](https://github.com/user-attachments/assets/e5516abd-1aac-4849-88d8-ba0cbeaa0c49)

**Comment by 17arindam** [comment]
@DharshiBalasubramaniyam please assign me this issue

**Comment by ayushbhjh** [comment]
@DharshiBalasubramaniyam i have idea of media queary please assign this task to me
