### ISSUE TITLE
[BUG]: In Delivery section  RESET button not working and also after submitting the form no successful message is there

### ISSUE THREAD

**Issue by shreyabajaj12** [DharshiBalasubramaniyam/ice-cream-parlour-website#361]
In the delivery Section after entering and submitting there is no successful message for the confirmation of form submission .
And also RESET button is not working.
I would like to fix these issue.
![Screenshot 2024-10-11 080547](https://github.com/user-attachments/assets/a2413572-826a-4181-937a-95ad9d796379)

@DharshiBalasubramaniyam if you find this issue suitable kindly assign it to me under hacktoberfest and GSSOC.

**Comment by shreyabajaj12** [comment]
@DharshiBalasubramaniyam kindly review it and assign it to me

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam kindly review it and assign it to me

Work on rest button is enough. no need to show success message. beacuse without backend implemetation showing success msg is not applicable.

**Comment by shreyabajaj12** [comment]
okeyy mam as you say
