### ISSUE TITLE
Styling Headings

### ISSUE THREAD

**Issue by Shrutibansal22** [DharshiBalasubramaniyam/ice-cream-parlour-website#368]
I would like to add CSS to the headings of different portions so that will bring more beauty in your amazing project .
Kindly assign me this work
![Screenshot 2024-10-11 130005](https://github.com/user-attachments/assets/205ec3de-008f-4a97-aeda-db87796cc018)
![Screenshot 2024-10-11 130010](https://github.com/user-attachments/assets/05296672-66a6-4221-a076-57642779c70a)

**Comment by ayushbhjh** [comment]
i Will solve this issue please assign me

**Comment by DharshiBalasubramaniyam** [comment]
Can you share any samples?

**Comment by Shrutibansal22** [comment]
![Screenshot 2024-10-11 170649](https://github.com/user-attachments/assets/f9b1cf85-dc59-4f37-aedc-0cf6489325f2)
![Screenshot 2024-10-11 170656](https://github.com/user-attachments/assets/cc3ccd5d-0865-4297-b1fb-1b402b0fac4e)

styling like this

**Comment by DharshiBalasubramaniyam** [comment]
Okay go ahead

**Comment by Shrutibansal22** [comment]
Thank u mam.
