### ISSUE TITLE
Feature: I can add blog section in your webiste 

### ISSUE THREAD

**Issue by Siddhant432** [DharshiBalasubramaniyam/ice-cream-parlour-website#384]
A blog section on a website serves several important purposes, enhancing both the user experience and the overall effectiveness of the site.

**Comment by DharshiBalasubramaniyam** [comment]
> A blog section on a website serves several important purposes, enhancing both the user experience and the overall effectiveness of the site.

Create a new page and link it to the footer

**Comment by Siddhant432** [comment]
Ok @DharshiBalasubramaniyam

**Comment by Siddhant432** [comment]
@DharshiBalasubramaniyam I have created pull request pls check.
