### ISSUE TITLE
In footer section of index.html, input box and button of newsletter is perfectly not aligned

### ISSUE THREAD

**Issue by Rohit72099** [DharshiBalasubramaniyam/ice-cream-parlour-website#399]
In footer section of index.html, input box and button of newsletter is perfectly not aligned
index.html
![image](https://github.com/user-attachments/assets/24dbd979-268d-4b97-a1f5-b9a01677ed79)

but in products.html, it is perfectly aligned
![image](https://github.com/user-attachments/assets/29d1a86a-80b8-497a-abee-4874b80dedb0)

@DharshiBalasubramaniyam if you find this issue suitable kindly assign it to me under hacktoberfest and GSSOC

**Comment by swati-204** [comment]
I want to work on this
