### ISSUE TITLE
Create login and sign up pages

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#4]
Login UI: 
![image](https://github.com/user-attachments/assets/24ba5d41-c77e-4828-909a-933a82fc1f47)

Sign up UI:
![image](https://github.com/user-attachments/assets/c69f20b2-70c1-4b29-9cc5-2bb4c216077f)
![image](https://github.com/user-attachments/assets/e510b424-eb2c-4ba3-a377-92afecfe627a)

Note:
- Kindly replace the gitlab logo with icyco logo.
- Kindly use separate style sheet.
- Kindly make sure that the pages are responsive.

**Comment by unnati-078** [comment]
please assign me this issue.

**Comment by hannah-maria** [comment]
would like to work on this, kindly assign me this issue!

**Comment by Inija-2503** [comment]
Assign me this issue i would like to work on it.

**Comment by DharshiBalasubramaniyam** [comment]
@unnati-078, the issue is assigned to you. All the best.

**Comment by unnati-078** [comment]
@DharshiBalasubramaniyam, Currently can't work on this please assign this to others.

**Comment by hannah-maria** [comment]
I am available to work on this, consider assigning it to me! @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Hi @hannah-maria, The issue is assigned to you!

**Comment by DharshiBalasubramaniyam** [comment]
> Hi @hannah-maria, The issue is assigned to you!

Do you like to work on this issue?

**Comment by hana-maria** [comment]
@DharshiBalasubramaniyam my account got suspended, working on getting it back. This is my new account. I'm still working on this. Can attach the mail regarding the assignment for proof

**Comment by hana-maria** [comment]
@DharshiBalasubramaniyam sorry for the delay! this is taking some time, i just made the login in page, is this fine?
i still need to insert a line on either side of the 'or sign in with' line
<img width="1470" alt="Screenshot 2024-10-05 at 8 56 44 AM" src="https://github.com/user-attachments/assets/6287d6dc-b34f-474e-97f5-db5e12ec06f2">

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam sorry for the delay! this is taking some time, i just made the login in page, is this fine? i still need to insert a line on either side of the 'or sign in with' line <img alt="Screenshot 2024-10-05 at 8 56 44 AM" width="1470" src="https://private-user-images.githubusercontent.com/183726622/373842875-6287d6dc-b34f-474e-97f5-db5e12ec06f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDE5NDYsIm5iZiI6MTcyODEwMTY0NiwicGF0aCI6Ii8xODM3MjY2MjIvMzczODQyODc1LTYyODdkNmRjLWIzNGYtNDc0ZS05N2Y1LWRiNWUxMmVjMDZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwNDE0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGY1MGQ5ZDMxNDdjNzk0Nzk2NTNiMTJiYzUwYjBhOGYwMjUyNzM5ZGViM2Q0YjhiNmJjMzRiZTFkNThmNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F3MydSeRUkAQyVBWdNps2jJz3t7pK2W6ZjxG9b3_v_s">

Yeah fine. Nice.

**Comment by hana-maria** [comment]
@DharshiBalasubramaniyam Alright! Can you tell me what elements should be responsive?

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Alright! Can you tell me what elements should be responsive?

Entire page should be responsive

**Comment by hana-maria** [comment]
@DharshiBalasubramaniyam Hi! I'm kinda confused about media queries, do you think you can help me out?

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Hi! I'm kinda confused about media queries, do you think you can help me out?

Okay leave responsive stuff. I'll handle it.

**Comment by hana-maria** [comment]
@DharshiBalasubramaniyam Alright! Let me try it out for sometime anyway.

**Comment by bhaviya18** [comment]
Hello sir I would like to work on this issue, kindly assign this task to me

**Comment by Codersweta7** [comment]
@DharshiBalasubramaniyam 
Assign me this issue 
I will add button to make it more responsive and User friendly using javascript

**Comment by Codersweta7** [comment]
@DharshiBalasubramaniyam 
Is there any issue I can work upon on your repository with hacktoberfest tag and levels between 1 , 2 ,3
