### ISSUE TITLE
Create new section for "Our Flavors"

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#411]
Create a new section in between the "hero" and "what we do for flavors.

Our flavors => regular, gelato,  sorbet, yogurt, non diary/vegen

Sample ui:

 
![image](https://github.com/user-attachments/assets/c4ef70c6-8704-485c-a55f-11ad8a2ce8fb)

**Comment by dharmesh191312** [comment]
Please assign me this issue.

**Comment by dharmesh191312** [comment]
@DharshiBalasubramaniyam Thankyou for assigning me, I am on it.

**Comment by dharmesh191312** [comment]
Hi @DharshiBalasubramaniyam ,
I have made a Pull Request, kindly check.

**Comment by ManjeshGowda06** [comment]
Hi, can I take this issue and work on it?
plaese assign this issue,  i will work on this
