### ISSUE TITLE
Create a new page "Gallary"

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#413]
Sample: [https://www.homersicecream.com/gallery](https://www.homersicecream.com/gallery)

**Comment by Rohit72099** [comment]
i want to work on this issue, kindly assign it to me under hacktoberfest and GSSOC

**Comment by Rohit72099** [comment]
can i work on this issue

**Comment by DharshiBalasubramaniyam** [comment]
Kindly follow the theme of the website. refer faq.html, catering.html for reference

**Comment by Rohit72099** [comment]
ok
