### ISSUE TITLE
Add proper title

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#414]
In the most of the pages title is not correctly specified. 

Kindly fix them:

index.html => ICYCO - HOME
products.html => ICYCO - PRODUCTS
delivery.html => ICYCO - DELIVERY

likewise...

**Comment by Rohit72099** [comment]
i want to work on this issue, kindly assign it to me under hacktoberfest and GSSOC
