### ISSUE TITLE
Change the current loader style

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#416]
Current one: 
![image](https://github.com/user-attachments/assets/dc301ddf-bd51-4275-a051-f8750dfb8df6)

**Comment by Rohit72099** [comment]
i want to work on this issue, kindly assign it to me under hacktoberfest and GSSOC

**Comment by Rohit72099** [comment]
can i work on this issue

**Comment by DharshiBalasubramaniyam** [comment]
> can i work on this issue

sure.
