### ISSUE TITLE
Create a separate section of flavours or types of ice cream we provide

### ISSUE THREAD

**Issue by ekta1810** [DharshiBalasubramaniyam/ice-cream-parlour-website#419]
we can make a separate page or section for flavours of ice cream that will be provided. For this we can use html, css and some javascript too, to make this more attractive.

**Comment by DharshiBalasubramaniyam** [comment]
> we can make a separate page or section for flavours of ice cream that will be provided. For this we can use html, css and some javascript too, to make this more attractive.

For this I already created an issue #411. If you like to work on that comment on that issue.
