### ISSUE TITLE
create a new section "WHY icyco?"

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#421]
Create the section before top reviews in index.html

Sample ui: 
![image](https://github.com/user-attachments/assets/0701e3cc-9f2c-4954-9ea9-289aaa94fcd6)

4 points to include:

1. Range of flavors
2. hygiene and food safety conditions
3. Best quality ingredients
4. fun and friendly atmosphere

**Comment by Rohit72099** [comment]
i want to work on this issue, kindly assign it to me under hacktoberfest and GSSOC

**Comment by vijaychandra1910** [comment]
please assign it to me I want to work on it. @DharshiBalasubramaniyam
