### ISSUE TITLE
change all buttons styles to make it look more attractive 

### ISSUE THREAD

**Issue by AmanKumar1115** [DharshiBalasubramaniyam/ice-cream-parlour-website#43]
@DharshiBalasubramaniyam  I want  to work this project as gssoc-ext, hactoberfest contributer.
Can you please assign this to me?

**Comment by vararaghu002** [comment]
Interested to work on this project, pls assign to me.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @AmanKumar1115, The issue is assigned to you... All the best!

**Comment by vararaghu002** [comment]
Thank you sir

**Comment by rohitsharma2610** [comment]
hey, i have great command in front-end development , so i want to work on this and make this site beautiful.

**Comment by rounakdey6** [comment]
Sir , i am full stack developer can you please assign this work to me?

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label
