### ISSUE TITLE
No nav bar in FAQ

### ISSUE THREAD

**Issue by CowTheGreat** [DharshiBalasubramaniyam/ice-cream-parlour-website#431]
![image](https://github.com/user-attachments/assets/9665147d-c9e9-4234-8d0f-4ae5cd3e2197)

adding nav bar to faq to navigarte back to home

**Comment by DharshiBalasubramaniyam** [comment]
Check now. the nav and the footer are there in the faq page. Can do this for blog.html. You have to add nav and footer to the blogs.html. You can refer faq.html for reference.

**Comment by aastikdas** [comment]
Hi @DharshiBalasubramaniyam ,
Can you assign me this issue, I'm a beginner and eager to learn. I’m committed to working on Open source, kindly give me an opportunity.

Thank you!

**Comment by DharshiBalasubramaniyam** [comment]
Sorry already solved by another person

**Comment by aastikdas** [comment]
Oh. okay thanks, Hoping to contribute in near future
