### ISSUE TITLE
create a page where customers can make combos of ice creams they prefer or customize it in any way they wish .

### ISSUE THREAD

**Issue by Vivisteria11** [DharshiBalasubramaniyam/ice-cream-parlour-website#432]
I want to create a page where the customers can choose beyond the available ice creams  and make their own custom ice creams and order them online .

**Comment by DharshiBalasubramaniyam** [comment]
can you share any samples?

**Comment by Vivisteria11** [comment]
yes ,suppose they want to have a combo of vanilla  and strawberry  ice cream,with sprinklers on top added with hot chocolate sauce .They can add all these elements to a list and create their combo .

**Comment by Vivisteria11** [comment]
hello ma'am ,the pull request linked here .What does it mean? Has this person already done this kind of change or should I work on it .I am a little confused

**Comment by DharshiBalasubramaniyam** [comment]
> hello ma'am ,the pull request linked here .What does it mean? Has this person already done this kind of change or should I work on it .I am a little confused

Don't worry about it. No one can work on others issues. Even though that happens, I ll not merge such prs

**Comment by Vivisteria11** [comment]
hello ,I am not able to see the website upon running .Its constantly loading but not resulting in the webpage .I followed the steps as in the readme doc. Any dependencies are to be downloaded?
