### ISSUE TITLE
Adding scrolling animation.

### ISSUE THREAD

**Issue by vijaychandra1910** [DharshiBalasubramaniyam/ice-cream-parlour-website#440]
Adding some scrolling animation to all the cards.

![Screenshot 2024-10-12 220232](https://github.com/user-attachments/assets/d5446436-d2da-4dc2-9df6-ad88409b51a7)

**Comment by vijaychandra1910** [comment]
please give it as level 2 @DharshiBalasubramaniyam

**Comment by vijaychandra1910** [comment]
because it take time for adding animation.

**Comment by DharshiBalasubramaniyam** [comment]
I am always increase or reduce the level based on your performance, after reviewing the pr @vijaychandra1910.

**Comment by vijaychandra1910** [comment]
ok thank you

**Comment by vijaychandra1910** [comment]
I will send you pull request again because I edited the oldone by mistake. @DharshiBalasubramaniyam
