### ISSUE TITLE
add Payment options

### ISSUE THREAD

**Issue by Amulya-B28** [DharshiBalasubramaniyam/ice-cream-parlour-website#441]
I would like to add payment options like upi,cash on delivery or card and payment details like name phno address and other options after clicking on check out button.
![image](https://github.com/user-attachments/assets/aa56c416-5891-47ec-b822-6f30f111df8a)
![image](https://github.com/user-attachments/assets/bd375e41-6af2-45a9-8319-e52181dd03a5)
![image](https://github.com/user-attachments/assets/4012b443-7a95-4c9d-8347-95b2e34813ea)

**Comment by Rupendra0** [comment]
nice thought but it includes backend i think

**Comment by Amulya-B28** [comment]
Im still learning backend so in this task ill be adding the template as shown above which works similar to login and sign up page it accepts the details and shows payment successful at the end...ill try to make it as simple as possible.

**Comment by DharshiBalasubramaniyam** [comment]
Actually this is a beginner friendly frontend project. I didn't plan to add backend for this. So I think without proper backend adding such page is not appropriate.
