### ISSUE TITLE
Add discount in Nav bar

### ISSUE THREAD

**Issue by Rupendra0** [DharshiBalasubramaniyam/ice-cream-parlour-website#442]
we have to add a discount section in navigation bar , by which we can directly target costumers that this website also have discounts.

we further divide the discount section into normal discount and student discount.

i am also able to do this work

**Comment by DharshiBalasubramaniyam** [comment]
Can you share some sample screenshots?

**Comment by Rupendra0** [comment]
Yeah
![Screenshot 2024-10-14 115025](https://github.com/user-attachments/assets/dc11a41b-4f37-45c0-9826-691f8a277b3c)
![Screenshot 2024-10-14 115341](https://github.com/user-attachments/assets/8ebe8c73-be5a-451b-909a-7ed29cc9f457)

**Comment by Rupendra0** [comment]
assign me this work i will do it

**Comment by SanikaBhalerao1345** [comment]
@DharshiBalasubramaniyam can i work on this issue and add more features like special deals/combos, new arrivals promotion code etc
