### ISSUE TITLE
In contact box, digits are exceeds from12 digits

### ISSUE THREAD

**Issue by Adityadhiman0** [DharshiBalasubramaniyam/ice-cream-parlour-website#443]
In contact box digits should have limit of 12 digits including country code and it should not accept alphabets. Which is good  for front-end user.
![Screenshot (41)](https://github.com/user-attachments/assets/37273e62-c332-4150-bdd4-501f3292f11a)
![Screenshot (42)](https://github.com/user-attachments/assets/d1c7915d-abf8-472c-bd2b-d9ff0210f5b6)

**Comment by Adityadhiman0** [comment]
Assign this issue to me and i will fix it in a day.

**Comment by Rupendra0** [comment]
i can fix this in 2-3 hours 
assign me !!

**Comment by Pinsu27** [comment]
assign me this issue
