### ISSUE TITLE
Adding a Favicon

### ISSUE THREAD

**Issue by Ishika-Gupta06** [DharshiBalasubramaniyam/ice-cream-parlour-website#445]
for better UI
feature priority =high

**Comment by Ishika-Gupta06** [comment]
@DharshiBalasubramaniyam **Assign me this under gssoc-ext,hacktoberfest and level-1,2,3**

**Comment by DharshiBalasubramaniyam** [comment]
do you mean the cion near the title?

**Comment by Ishika-Gupta06** [comment]
yes
