### ISSUE TITLE
Missing links in the useful links section at footer

### ISSUE THREAD

**Issue by sruthi070** [DharshiBalasubramaniyam/ice-cream-parlour-website#45]
![image](https://github.com/user-attachments/assets/2f7a0e7f-3932-4182-b89e-265ff329cf83)

**Comment by sruthi070** [comment]
@DharshiBalasubramaniyam could you please assign me this issue under Gssoc'24 extd

**Comment by clownfish1805** [comment]
@DharshiBalasubramaniyam I would like to work on this issue. Please assign me under GSSOC'24 extended

**Comment by T-Fathima** [comment]
@DharshiBalasubramaniyam I would to fix this issue.
Please assign me under GSSOC'24 extended
