### ISSUE TITLE
Improve ui of nav bar( while scrolling little transparent)

### ISSUE THREAD

**Issue by justynigam** [DharshiBalasubramaniyam/ice-cream-parlour-website#450]
-it willl look more enhance []
![Screenshot 2024-10-02 135820](https://github.com/user-attachments/assets/c11bf5d6-66b6-45d1-8649-0ce22f0bfc36)
-while scrolling it will appear
- im a gssoc contributer

**Comment by DharshiBalasubramaniyam** [comment]
Sorry can you explain more?

**Comment by justynigam** [comment]
Like when we are not scrolling it will look normal like ur nav bar but when u start scroll it will look little bit tranparent background little whitish with banground transparent
