### ISSUE TITLE
Improve Footer Layout for Mobile View

### ISSUE THREAD

**Issue by manthanmk66** [DharshiBalasubramaniyam/ice-cream-parlour-website#452]
The current footer layout on mobile devices appears cluttered and vertically long, which affects the user experience. To improve visibility and create a minimalist design, the footer content should be organized in a responsive grid layout. This will ensure that the content is well-distributed and easier to navigate on smaller screens.
![image](https://github.com/user-attachments/assets/6de54afe-6df2-4ee3-86b0-5c37d6333800)

**Comment by DharshiBalasubramaniyam** [comment]
Now solved
