### ISSUE TITLE
issue about not visible button on navbar

### ISSUE THREAD

**Issue by dipak2005** [DharshiBalasubramaniyam/ice-cream-parlour-website#454]
in mobile view in navigation bar button are not visible because the incorrect color matching purple and pink and font size and font weight 
![Screenshot 2024-10-13 121422](https://github.com/user-attachments/assets/8a90eeb8-3113-4f98-a789-27e270a115b2)
color contrast rate for this ui :
![Screenshot 2024-10-13 121806](https://github.com/user-attachments/assets/12e9ef59-e796-4f1e-882a-9f5a1721e3e1)

**Comment by DharshiBalasubramaniyam** [comment]
I cannot see your screenshots properly!

**Comment by dipak2005** [comment]
> I cannot see your screenshots properly!

please check i uploaded properly screen shot of issues

**Comment by harshita2303** [comment]
I want to work on this please assign this issue to me @dipak2005

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by dipak2005** [comment]
> I want to work on this please assign this issue to me @dipak2005 

I'm not the owner of this repo you tell @DharshiBalasubramaniyam to assign the issue
