### ISSUE TITLE
[style] The text is not visible clearly.

### ISSUE THREAD

**Issue by hadifarousheen** [DharshiBalasubramaniyam/ice-cream-parlour-website#466]
Because the background colour and the text colour is same. The text is not visible clearly. I want to fix this issue.
![Screenshot_20241013-165744_Chrome](https://github.com/user-attachments/assets/d88838d7-63e7-4bb9-b807-742d2c27f73d)

**Comment by DharshiBalasubramaniyam** [comment]
Now solved!
