### ISSUE TITLE
Add Star Rating Feature for Ice Cream Products and feedback of coustomer

### ISSUE THREAD

**Issue by simmi-verma** [DharshiBalasubramaniyam/ice-cream-parlour-website#472]
To enhance customer interaction and gather feedback on our ice cream offerings, I propose adding a star rating feature to each ice cream product on the website/app and   adding a feedback section specifically for customers who purchase ice cream. This will help us understand their preferences and improve our products and services.

**Comment by simmi-verma** [comment]
Hello , I noticed that the issue has been closed, but it’s still assigned to me. Can I continue working on this, or should I focus on other open issues instead? Please let me know. Thank you

**Comment by DharshiBalasubramaniyam** [comment]
> Hello , I noticed that the issue has been closed, but it’s still assigned to me. Can I continue working on this, or should I focus on other open issues instead? Please let me know. Thank you

You can create new issue or check for existing issues with good first issue label

**Comment by simmi-verma** [comment]
ok
