### ISSUE TITLE
Change the ui of the reviews section in index.html

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#477]
The ui: 
![image](https://github.com/user-attachments/assets/e4501bcc-8982-4541-9cb2-27d41f8a9989)

**Comment by mishraRj** [comment]
I like to contribute in this issue

**Comment by mishraRj** [comment]
Mam! Do I need to make the review section UI like the UI in Screenshot above ?

**Comment by DharshiBalasubramaniyam** [comment]
> Mam! Do I need to make the review section UI like the UI in Screenshot above ?

yes

**Comment by mishraRj** [comment]
> > Mam! Do I need to make the review section UI like the UI in Screenshot above ?
> 
> yes. the background not needed

Can you plz tell me the name of CSS file in your project which has stylings of review section ?

**Comment by DharshiBalasubramaniyam** [comment]
styles.css under styles folder

**Comment by mishraRj** [comment]
Index.html file is not opening. It only showing processing and animation of ice cream rotating at a place only when I am trying to test index.html file locally.

**Comment by mishraRj** [comment]
And one genera doubt! If I made the UI of your review section like UI in screenshot, will not it stop your swiper slider functionality. I mean if all the reviews will be in same block there will be no need of sliding functionality.

**Comment by mishraRj** [comment]
Kindly describe your issue lil bit to me about what I need to do and what to not.. 
Please provide me a clearer screen shot of UI for review section you wanted.

I am a new comer to open source contribution. Plz guide me a lil, I will really appreciate your guidance.
Thankyou.

**Comment by DharshiBalasubramaniyam** [comment]
Slider functionality is not needed. Display 6 boxes 1 is for title and other 5 are reviews. Yiu can use flexbox or grid for this. And could you able to resolve the issue with the index.html

**Comment by mishraRj** [comment]
> Slider functionality is not needed. Display 6 boxes 1 is for title and other 5 are reviews. Yiu can use flexbox or grid for this. And could you able to resolve the issue with the index.html

yes I will definitely gonna solve this.
