### ISSUE TITLE
Blogs page not align with our theme

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#480]
1. Add nav bar
2. Add footer
3. Add preloader, bottom to top button, top scroll bar indicator
4. Remove theme switch
5. Change the font family
6. Create separate file for styles under styles folder
7. Check mobile responsive

Refer faq.html file to learn how the nav, preloader, bottom to top button, top scroll bar indicator and the footer are added.

**Comment by Adarsh-Chaubey03** [comment]
please assign me this task @DharshiBalasubramaniyam
