### ISSUE TITLE
Change nav icon to X when the nav is open

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#483]
When the nav is open the icon is not changing. 

So change it to X when the nav is open and change it to hamburger menu when the nav is closed.

![image](https://github.com/user-attachments/assets/6c8a41a9-a7aa-4118-81e1-afd57c76cd4c)

**Comment by T-Rahul-prabhu-38** [comment]
can you assign me this i can fix this.

**Comment by ManjeshGowda06** [comment]
please assign this work to me
