### ISSUE TITLE
Feature Request 📕: Add Dark Mode to the Ice Cream Parlour Website

### ISSUE THREAD

**Issue by rixvi0123** [DharshiBalasubramaniyam/ice-cream-parlour-website#490]
Description:
This issue is to implement a dark mode feature on the Ice Cream Parlour website (https://ice-cream-parlour-website-one.vercel.app/). Currently, the site uses a light theme by default. Adding a dark mode would enhance the user experience, especially for those who prefer browsing in low-light environments.

Requirements:
CSS: Create a dark theme style sheet or modify existing CSS to support dark mode, with inverted color schemes:

- Dark background colors (#121212 or similar).
- Light text colors (white or light gray).
- Adjustments to other UI elements (buttons, borders, etc.) to match the dark theme.
- Toggle Switch: Add a toggle button to the header or navigation area allowing users to switch between light and dark modes.

JavaScript: Use JavaScript to toggle dark mode on and off.

Smooth Transition: Ensure a smooth transition effect between light and dark modes using CSS transitions.

Additional Details:
The dark mode should not affect the overall aesthetics of the website (e.g., ice cream imagery, branding colors).
Acceptance Criteria:
- [ ]  A working dark mode toggle button.
- [ ] CSS updated with a fully functional dark mode.
- [ ]  No visual glitches or loss of design consistency in dark mode.

**Comment by rixvi0123** [comment]
@DharshiBalasubramaniyam please look in it

**Comment by mishraRj** [comment]
I am looking frwd to contribute in this issue...Plz assign this to me.

**Comment by mishraRj** [comment]
@DharshiBalasubramaniyam I completed the code working 1.5 hours to update dark theme toggle in your website. But you closed the issue.
Plz consider my Dark theme updated code and reopen this issue otherwise my efforts will be wasted.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam I completed the code working 1.5 hours to update dark theme toggle in your website. But you closed the issue. Plz consider my Dark theme updated code and reopen this issue otherwise my efforts will be wasted.

Why did you start working before assigning. No one allowed to work on an issue before assigning.. Kindly go through the contribution guidelines of gssoc-ext program
