### ISSUE TITLE
Replace GitHub Login Option with Facebook

### ISSUE THREAD

**Issue by JomanaMahmoud** [DharshiBalasubramaniyam/ice-cream-parlour-website#497]
<img src="https://github.com/user-attachments/assets/741936d1-b5b8-4c86-b370-a9191a0fea3b" width="40%">
<img src="https://github.com/user-attachments/assets/9a97192e-730e-457a-b935-d84789438f49" width="40%">

The GitHub login option on the login and signup pages seems irrelevant for users visiting an ice cream website. It would be more appropriate to replace this option with a **Facebook** login, which is more commonly used by such users.

I would like to make this change. Please assign this issue to me, as I am a contributor in **GSSoC-ext** and **Hacktoberfest**.

**Comment by Muskan753951** [comment]
i would like to make changes on this project . Please Assign it to me
