### ISSUE TITLE
Add faqs section

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#5]
Kindly add the faq section after contact.

Below are some sample questions and answers you may/may not use.

![Screenshot (44)](https://github.com/user-attachments/assets/800e2b65-7e81-4d7f-a4b9-044040222a86)

![Screenshot (45)](https://github.com/user-attachments/assets/1d25912e-1cc5-4212-ac79-b90563979f07)

**Comment by mrvishalsharma01** [comment]
can you please assign me this issue?

**Comment by Web-Dev-Learner** [comment]
i'm ready to improve  FAQ section can you assign the issue and add labels to this issue

**Comment by hannah-maria** [comment]
Would like to work on this, kindly assign me this issue!

**Comment by Roopalgn** [comment]
Can u kindly assign me this issue.I am positive that my knowledge in frontend can help u fixing this issue.
Also can u please assign the appropiate tags to the issue i.e. - gssoc-ext,hacktoberfest and level

**Comment by Gaurav075** [comment]
Can you please assign this issue to me? I am a beginner ,give me a chance.

**Comment by DharshiBalasubramaniyam** [comment]
@hannah-maria, the issue is assigned to you. All the best.
