### ISSUE TITLE
Improvement to README file

### ISSUE THREAD

**Issue by adityakalburgi** [DharshiBalasubramaniyam/ice-cream-parlour-website#50]
Hi!
I'd like to contribute by improving the README file. Could you please assign this issue to me? Thanks!

**Comment by DharshiBalasubramaniyam** [comment]
If possible add rules to be followed when creating issues and prs as per the gssoc guidelines

**Comment by adityakalburgi** [comment]
@DharshiBalasubramaniyam ok I will do it

**Comment by adityakalburgi** [comment]
hi! @DharshiBalasubramaniyam i have submitted a PR please have a look!

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
