### ISSUE TITLE
change in privacy policy section 

### ISSUE THREAD

**Issue by Kajalmehta29** [DharshiBalasubramaniyam/ice-cream-parlour-website#506]
<img width="601" alt="Screenshot 2024-10-13 at 11 44 10 PM" src="https://github.com/user-attachments/assets/6d6c79e2-21df-46c5-89fa-64ca8202aba0">

These points should be written in bullets or something.I want to fix this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Kajalmehta29, Actually there are so many changes to do in the privacy policy page.

1. Add nav bar
2. Add footer
3. Add preloader, bottom to top button, top scroll bar indicator
4. Change the font family according to our theme
5. Create separate file for styles under styles folder
6. Check mobile responsive

You can refer faq.html file to learn how the nav, preloader, bottom to top button, top scroll bar indicator and the footer are added.

Can you do this? I can provide level 3 label.

**Comment by Kajalmehta29** [comment]
hey @DharshiBalasubramaniyam 
Yes I can do this. 
Thankyou for considering.

**Comment by Kajalmehta29** [comment]
Hey @DharshiBalasubramaniyam 
Please have a look.
