### ISSUE TITLE
Fix "Header Navigation Links" to Correctly Navigate to Corresponding Sections of the Page

### ISSUE THREAD

**Issue by clownfish1805** [DharshiBalasubramaniyam/ice-cream-parlour-website#51]
![Screenshot 2024-10-02 135022](https://github.com/user-attachments/assets/3c3b0041-71bf-46a5-a230-3190059c8199)

@DharshiBalasubramaniyam 
I would like to work on this issue.
To correctly navigate the header to its corresponding sections of the page.

Please add me to this issue under **GSSOC'24 extended**

**Comment by Ishika-codeit** [comment]
hey,very excited to work on this issue....
kindly assign it 
thank you!!

**Comment by 4F24L** [comment]
@DharshiBalasubramaniyam CAn you assign this , So I can start work on this issue !
