### ISSUE TITLE
Add Hover Effects to Static Cards in IcyCo Section

### ISSUE THREAD

**Issue by neeru24** [DharshiBalasubramaniyam/ice-cream-parlour-website#511]
The cards in the IcyCo section are currently static and lack interactivity. To enhance user experience and visual appeal, we would like to implement hover effects on these cards. This will provide users with feedback when they hover over the cards and make the interface more engaging.

**Task:**

- Add hover effects (e.g., scale, shadow, color change) to the cards in the IcyCo section.
- Ensure the hover effects are smooth and consistent with the overall design of the site.
- Test the implementation for responsiveness and cross-browser compatibility.

**Expected Outcome:**
The cards in the IcyCo section should have dynamic hover effects that improve interactivity and user engagement.

![image](https://github.com/user-attachments/assets/0655c02d-2fb4-46c6-8221-afb2b8f325c1)

**Comment by Muskan753951** [comment]
i want to work on this project. Please Assign it to me
