### ISSUE TITLE
Redirection of "Order Online" to "Products" page.

### ISSUE THREAD

**Issue by rees8** [DharshiBalasubramaniyam/ice-cream-parlour-website#520]
![image](https://github.com/user-attachments/assets/f378241d-09c1-423b-8e5e-464441ebffa1)

So there's an "Order Online" option included in the "Gallery" section which on clicking doesn't redirect the user to the "Products" page.
I would like to modify the code so that the user can proceed to explore the available products @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Hi @rees8, Actually, I thought to remove that button. Can you?

**Comment by rees8** [comment]
Ok, that works too. I can do it.
