### ISSUE TITLE
Added more State in the delivery section.

### ISSUE THREAD

**Issue by itskundanhere** [DharshiBalasubramaniyam/ice-cream-parlour-website#525]
![Screenshot 2024-10-14 143653](https://github.com/user-attachments/assets/0c076c5e-02cd-4088-8777-9f562e111343)

I want to added the more state in the delivery section. By added the more state it enhance the improving the delivery location.
Please assign me for fixing this issues @DharshiBalasubramaniyam .

**Comment by DharshiBalasubramaniyam** [comment]
Hi @itskundanhere, Actually i am in Sri lanka. We have 25 states. I want to display them instead. Can you? 

1. Colombo

2. Gampaha

3. Kalutara

4. Kandy

5. Matale

6. Nuwara Eliya

7. Galle

8. Matara

9. Hambantota

10. Jaffna

11. Kilinochchi[[1]](http://www.commonlii.org/lk/legis/const/2000/27.html#fn1)

12. Mannar

13. Vavuniya

14. Mullaitivu

15. Batticaloa

16. Ampara

17. Trincomalee

18. Kurunegala

19. Puttalam

20. Anuradhapura

21. Polonnaruwa

22. Badulla

23. Moneragala

24. Ratnapura

25. Kegalle

**Comment by itskundanhere** [comment]
@DharshiBalasubramaniyam sure i will.
