### ISSUE TITLE
Adding gallery in Navbar of other Pages

### ISSUE THREAD

**Issue by Rohit72099** [DharshiBalasubramaniyam/ice-cream-parlour-website#527]
I want to add gallery in navbar of other pages like Product , Delivery etc.

![image](https://github.com/user-attachments/assets/7519bc68-9be7-46db-9be4-73a602b013e5)
![image](https://github.com/user-attachments/assets/2cf53404-b94e-484f-8a96-3bc4ad79f862)
![image](https://github.com/user-attachments/assets/c261160f-9c80-4eb0-871f-8b7fa9d271ee)

**Comment by Rohit72099** [comment]
@DharshiBalasubramaniyam if find this issue suitable kindly assign this to me under hactoberfest and GSSOC

**Comment by DharshiBalasubramaniyam** [comment]
@Rohit72099, For now add gallary link to the footer of all pages. And remove the gallary link from the home page nav as well.

**Comment by Rohit72099** [comment]
Ok
