### ISSUE TITLE
Make Copyright Year Dynamic in Footer

### ISSUE THREAD

**Issue by we-nita** [DharshiBalasubramaniyam/ice-cream-parlour-website#546]
# Description:
The copyright year is currently hardcoded in the footer section of the website. This requires manual updates each year, which is not ideal for maintaining the codebase.

# Suggested Solution: 
Implement a dynamic method to automatically update the copyright year. This can be done using JavaScript or by utilizing server-side code, depending on the technology stack used.

I can provide a pull request with the solution if needed.
Please assign me the issue with gssoc-ext, level, and hactoctober fest label

**Comment by we-nita** [comment]
Thank you for assigning me the issue. Could you please also assign the gssoc-ext, level, and hactoctober fest labels to it for better tracking?

**Comment by DharshiBalasubramaniyam** [comment]
Can you do it for all pages?

**Comment by we-nita** [comment]
Yes, I will update it for all pages.
