### ISSUE TITLE
show order confirmed after clicking checkout

### ISSUE THREAD

**Issue by Amulya-B28** [DharshiBalasubramaniyam/ice-cream-parlour-website#551]
I want to add a pop up or new page that shows order is confirmed after clicking the check out button....I want to add it beacuse it feels kind of incomplete when you want to purchase the products  in the website. Please assign me this task.

![image](https://github.com/user-attachments/assets/7412d6ad-7a9b-4b39-acfc-b1bc05a61b25)

**Comment by DharshiBalasubramaniyam** [comment]
Without backend implementation showing success message is not appropriate.
