### ISSUE TITLE
rresolve overlap in gallery section

### ISSUE THREAD

**Issue by vijaychandra1910** [DharshiBalasubramaniyam/ice-cream-parlour-website#553]
![Screenshot 2024-10-14 223030](https://github.com/user-attachments/assets/c8e623bc-2829-4fc4-88e6-ee3819155ac4)

Here the above content are overlap to the navbar. I want to work for resolving this.

**Comment by ManjeshGowda06** [comment]
please assigne this work to me i will do this

**Comment by vijaychandra1910** [comment]
I will work on it.

**Comment by vijaychandra1910** [comment]
issue number #553 completed #593 please check and merge it. 
@DharshiBalasubramaniyam
