### ISSUE TITLE
Improve social media icons with enhancement in hover effects. 

### ISSUE THREAD

**Issue by VidhanThakur09** [DharshiBalasubramaniyam/ice-cream-parlour-website#573]
### Description
The current  social media icons have very basic styling, improving social media icon style and enhancing the styling would greatly improve the user experience and website presentation

### Describe the solution you'd like

- Format  social media for better visual appeal.
- Improving the hover effects on social media icons. 

### Problems 

https://github.com/user-attachments/assets/5beed34d-adfd-4482-9ed7-3f7d08588854

### Solution 

**After improving social media Icons / Mocks**

https://github.com/user-attachments/assets/c8a84fbe-a0ea-4644-b457-038de2cc9d8f

@DharshiBalasubramaniyam  can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by DharshiBalasubramaniyam** [comment]
In the footer section this one is not needed. you can do this for social icons in the login-signup pages?

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me. I will gladly optimize the social media icons on the login and sign-up pages.
