### ISSUE TITLE
Add hover effects to the 'Why IcyCo' section.

### ISSUE THREAD

**Issue by Sadab-Hussain** [DharshiBalasubramaniyam/ice-cream-parlour-website#581]
Hii,
I would like to add some CSS to the 'Why IcyCo' section to enhance the user experience. Please assign this issue to me.

![Screenshot 2024-10-15 155331](https://github.com/user-attachments/assets/4c6eab13-0b92-466c-93f8-ff96edc492b5)

Thank you @DharshiBalasubramaniyam

**Comment by ManjeshGowda06** [comment]
please assign this work to me i will work on this its my kind request

**Comment by Arghya-Chakraborty0812** [comment]
please assign this issue to me @DharshiBalasubramaniyam
