### ISSUE TITLE
Enhancement: Improve Navbar Interactivity with Hover Effects and Animations

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [DharshiBalasubramaniyam/ice-cream-parlour-website#582]
**Summary of the Problem:**
The current navbar design lacks engaging hover effects for the logo and navigation items. Additionally, the login and cart icons do not have any animations, making the overall user experience less interactive and visually appealing. By implementing these enhancements, we can significantly improve the aesthetics and user engagement of the website.

## Expected Behavior
- **Logo**: The logo should have a noticeable hover effect (e.g., color change, slight scale, or glow effect) to attract user attention.
- **Nav Items**: Each navigation item should feature engaging hover effects, such as color transitions, underlines, or animations, to enhance interactivity.
- **Login and Cart Icons**: These icons should include animated hover effects (e.g., bounce, scale, or spin) to create a more dynamic experience and encourage user interaction.

## Current Behavior
- The logo remains static without any hover effects, failing to engage users visually.
- Navigation items lack interactivity, making the navbar feel flat and uninspiring.
- Login and cart icons do not respond to user actions, which can lead to a less engaging experience.

## Steps to Reproduce
1. Open the website and observe the navbar.
2. Hover over the logo, navigation items, login icon, and cart icon.
3. Note the absence of hover effects and animations.

 
## Screenshot

![navbar9](https://github.com/user-attachments/assets/32fe3e8f-15a5-4bd5-beca-f7bdffdd001b)

 

## Additional Context
Enhancing the navbar's interactivity will not only improve the visual appeal of the website but also create a more engaging user experience. Effective use of hover effects and animations can guide users' attention to important elements and encourage interaction.
 
## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

**Comment by DharshiBalasubramaniyam** [comment]
You can add hover effects for logo and icons in the nav.
