### ISSUE TITLE
 Enhancement: Improve Contact Form UI and Add Border Animation

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [DharshiBalasubramaniyam/ice-cream-parlour-website#583]
**Summary of the Problem:**
The current design of the "Contact Us" section lacks visual appeal, particularly the contact form. The input fields are too large, and the placeholder text occupies excessive space, making it difficult for users to focus on the fields. Additionally, the overall interactivity of the form could be enhanced with border animations to make it more engaging for users.

## Expected Behavior
- **Input Field Size**: The overall size of the input fields should be reduced to create a more balanced and visually appealing design.
- **Placeholder Size**: The size of the placeholder text should be adjusted to fit well within the input fields without overwhelming the user.
- **Border Animation**: Adding a subtle border animation to the input fields when focused will create a more interactive experience and draw attention to the contact form.

## Current Behavior
- The input fields in the contact form are oversized, which can be visually distracting.
- The placeholder text in the input fields takes up too much space, affecting readability.
- The input fields lack any interactive elements, making the form feel static and uninviting.

## Steps to Reproduce
1. Navigate to the "Contact Us" section of the website.
2. Observe the size of the input fields and the placeholder text.
3. Note the lack of interactive elements such as animations.

 

## Screenshots
 
![contactus](https://github.com/user-attachments/assets/3d1f4f1e-001f-451a-af12-b79df391b23c)

## Additional Context
Improving the design of the contact form will enhance user engagement and create a more polished appearance for the website. Border animations can make the form feel more dynamic and inviting, encouraging users to fill it out.

 

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

**Comment by nigam-divyanshi-dev** [comment]
please assign this to me under gssoc and hacktoberfest tag..so that i can contribute...
