### ISSUE TITLE
 Enhancement: Improve Footer Interactivity with Hover Effects and Animations

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [DharshiBalasubramaniyam/ice-cream-parlour-website#585]
**Summary of the Problem:**
The current design of the footer lacks engaging hover effects for the headers and footer items. Additionally, the social media icons do not have any interactive elements, making the footer feel static. By implementing hover effects and animations, we can significantly improve the visual appeal and user engagement of the footer section.

## Expected Behavior
- **Header Hover Effect**: Headers in the footer should have noticeable hover effects (e.g., color change or underline) to attract user attention.
- **Footer Items**: Implement an underline animation on footer items when hovered over, enhancing interactivity and visual appeal.
- **Social Media Icons**: Add a 3D hover effect on social media icons to create a more dynamic experience that encourages user interaction.

## Current Behavior
- The headers in the footer remain static without any hover effects, failing to engage users visually.
- Footer items lack interactivity, making the footer feel flat and uninspiring.
- Social media icons do not respond to user actions, leading to a less engaging experience.

## Steps to Reproduce
1. Scroll down to the footer section of the website.
2. Observe the headers and footer items when hovered over.
3. Note the lack of interactive elements such as animations on the social media icons.

 

## Screenshots
 
![footer 2](https://github.com/user-attachments/assets/d2f3d224-915a-4a41-9bfa-2cf8b9040e31)

## Additional Context
Enhancing the footer's interactivity will not only improve its visual appeal but also create a more engaging user experience. Effective use of hover effects and animations can guide users' attention to important elements and encourage interaction.
 

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

**Comment by ManjeshGowda06** [comment]
Hi, can I take this issue and work on it?
please assign this work to me i will work on this
