### ISSUE TITLE
[BUG] Extra space between home page and find your taste section

### ISSUE THREAD

**Issue by Rohit72099** [DharshiBalasubramaniyam/ice-cream-parlour-website#587]
Extra space between home page and find your taste section in index.html
![image](https://github.com/user-attachments/assets/1edbae3c-07fe-4d5a-ae26-3a70a7bca0c9)

@DharshiBalasubramaniyam if find this issue suitable kindly assign it me under hacktoberfest and GSSoC

**Comment by noobremon** [comment]
Please assign this to me
