### ISSUE TITLE
Change the loader style

### ISSUE THREAD

**Issue by Abankita** [DharshiBalasubramaniyam/ice-cream-parlour-website#588]
The present loader is good but we can make it more visually appealing by replacing it by a flavour wheel. This loader will consist of a spinning wheel with different ice cream flavor sections. 
@DharshiBalasubramaniyam

**Comment by SarangAhlawat** [comment]
I want to work on this issue and can add an attractive loader that'll even make visitors curious, please assign it to me under GSSoC'24 - Extd!
Also add gssoc-ext and level label.
