### ISSUE TITLE
Contact us page update with better styling and relevant UI

### ISSUE THREAD

**Issue by 770navyasharma** [DharshiBalasubramaniyam/ice-cream-parlour-website#59]
The contact us section can be made much more appealing and relevant to the website and is very simple looking right now also more transitions and gradient can be added 

I can resolve this issue ! Please assign it to me! Also add tags hacktoberfest, gssoc-extd, level

<img width="1443" alt="Screenshot 2024-10-02 at 6 33 03 PM" src="https://github.com/user-attachments/assets/f223fc35-e28c-45a2-9e84-d033253f88da">

**Comment by Shailjaa30** [comment]
please assign me this issue
