### ISSUE TITLE
Improved UI of Footer Section Add hover effecst in it

### ISSUE THREAD

**Issue by sanikamandale17** [DharshiBalasubramaniyam/ice-cream-parlour-website#590]
want to add hover effects in footer section and make it more interactive
![image](https://github.com/user-attachments/assets/843df4bd-b10e-41af-bd44-c2ad58ab96d4)

**Comment by noobremon** [comment]
Please assign this issue to me

**Comment by Shrinidhi-Nadig** [comment]
please assign this issue to me because I found a small mistake in the footer section and i am going to fixx it up..
