### ISSUE TITLE
dark and light toggle 

### ISSUE THREAD

**Issue by sv410** [DharshiBalasubramaniyam/ice-cream-parlour-website#591]
![WhatsApp Image 2024-10-15 at 12 05 39 PM](https://github.com/user-attachments/assets/1e6b0462-7274-4fff-a52f-bba73a209e72)
![WhatsApp Image 2024-10-15 at 12 06 01 PM](https://github.com/user-attachments/assets/a94ca5f3-5782-4e82-9708-074907542b26)

**Comment by SarangAhlawat** [comment]
I want to work on this issue, please assign it to me under GSSoC'24 - Extd!
Also add gssoc-ext and level label.
