### ISSUE TITLE
Create seperate page for products

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#6]
- Create a seperate file named `products.html`.
- Display the products there. (Use same code in the index.html)
- The products related scripts are in the `scripts/products.js` file.
- Kindly lake sure that the filtering and cart are working correctly in the new product page.
- Kindly don't remove the product section from `index.html` for testing purposes.
- Add the navbar and footer in this page.

**Comment by unnati-078** [comment]
please assign me this issue.

**Comment by Web-Dev-Learner** [comment]
i'm ready to improve section can you assign the issue and add labels to this issue.

**Comment by sweta123761** [comment]
assign that to me . through my knowledge of external css your mentioned points could be applied and a wonderful page for your website would be created

**Comment by Anushka184** [comment]
Assign me this task @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
@sweta123761, the issue is assigned to you. All the best.

**Comment by mahitha63** [comment]
@DharshiBalasubramaniyam I would love to solve this issue, assign this to me.

**Comment by DharshiBalasubramaniyam** [comment]
@sweta123761, any updates?

**Comment by sweta123761** [comment]
Give me 2 more days

**Comment by Codersweta7** [comment]
@DharshiBalasubramaniyam 
Please assign me this issue ....I want to work upon this

**Comment by DharshiBalasubramaniyam** [comment]
@sweta123761 I am closing the issue. It was about 1 week, from you assigned.

**Comment by Codersweta7** [comment]
@DharshiBalasubramaniyam 
Pleas assign me at the place of closing the issue
