### ISSUE TITLE
FAQ section update

### ISSUE THREAD

**Issue by 770navyasharma** [DharshiBalasubramaniyam/ice-cream-parlour-website#61]
The faqs section can be made more better by changing the arrow as we click on it also proper card effects can be added and answers should have more fascinating appearance 

@DharshiBalasubramaniyam Please assign this to me and add hacktoberfest and gssoc tag with level

<img width="1407" alt="Screenshot 2024-10-02 at 6 49 54 PM" src="https://github.com/user-attachments/assets/9195a7fd-4a25-4667-beb1-4e653bc40d0f">

**Comment by Himanshupri206** [comment]
I would like to work on it. Please assign it to me.
And label it under gssoc-ext

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me under hactoberfest
