### ISSUE TITLE
Navigation in Footer to different pages

### ISSUE THREAD

**Issue by saumyayadav25** [DharshiBalasubramaniyam/ice-cream-parlour-website#639]
Update footer with links for navigation to different pages.
1) In home page, there is no navigation for products
2) In other pages footer section, the navigation link for home and few other are not there, it does'nt redirect to that page from footer links.

**Comment by DharshiBalasubramaniyam** [comment]
I need some changes in footer. 

1. Remove flavor links.
2. In the useful links remove all the link which are not implemented yet (like about, customer agreement). For others provide suitable links. 

Can you @saumyayadav25? I need this changes in all html files.

**Comment by saumyayadav25** [comment]
@DharshiBalasubramaniyam sure i will do it.
