### ISSUE TITLE
[Enhance]: Search bar not working problem in Dine in page .

### ISSUE THREAD

**Issue by Jashwanth-rit** [DharshiBalasubramaniyam/ice-cream-parlour-website#659]
description:
 impliment search bar functionality , 

steps to reproduce :

1. go to dine-in page 
2. type in search box 
3. click on search icon
4. no changes

![Screenshot 2024-10-17 115738](https://github.com/user-attachments/assets/3780f228-4641-442d-a0ba-39eff55a9156)

**Comment by KomaLGoyaL02** [comment]
I can solve this very easily please assign it to me

**Comment by DharshiBalasubramaniyam** [comment]
@Jashwanth-rit, How will you solve this problem?

**Comment by Jashwanth-rit** [comment]
Just adding more addresses to database and as we search in search box , query goes to database and searches for address we enter , and fetch and display on screen.

**Comment by DharshiBalasubramaniyam** [comment]
We don't have database connection.

**Comment by Jashwanth-rit** [comment]
Ok then ,
