### ISSUE TITLE
[Feat]: onclick of any of the icecream, it should show the description of that ice-cream.

### ISSUE THREAD

**Issue by Jashwanth-rit** [DharshiBalasubramaniyam/ice-cream-parlour-website#660]
description:
onclicking on any of the ice-cream , that should travel us to ew page which shows us description about ice-cream 
and below , related ice-creams

![Screenshot 2024-10-17 115738](https://github.com/user-attachments/assets/7487253d-adef-4cbb-b95f-f8d76edc6257)

Kindly add Gssoc and Hacktoberfest tag and assign it to me ,

**Comment by KomaLGoyaL02** [comment]
kindly request to you please assign it to me
