### ISSUE TITLE
Adding issue and PR Templates

### ISSUE THREAD

**Issue by Khushalsarode** [DharshiBalasubramaniyam/ice-cream-parlour-website#67]
- making style adjustment for FAQ section
- adding templates for raising issue and raising PR with label for gssoc, feature, documentation, improvement & required tags
- level tag will be leaved as its owner authority!

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Khushalsarode faq section improvement not needed because it assigned some one else. You can add issue and pr templetes.
