### ISSUE TITLE
Add Toggle Dark Mode Button with Attractive Icons

### ISSUE THREAD

**Issue by Manojkumar2806** [DharshiBalasubramaniyam/ice-cream-parlour-website#674]
Implement a dark mode toggle button on the website to enhance user experience. The button should include eye-catching icons that smoothly switch between light and dark themes. The feature should be responsive, ensuring usability across various devices. Utilize CSS transitions for a sleek, animated effect when toggling between modes.

**Comment by mishraRj** [comment]
Hi
I have already solved the issue and I am raising the PR, plz review it.
