### ISSUE TITLE
[Feat]: Enhance search Bar on products page

### ISSUE THREAD

**Issue by Sudhanshu248** [DharshiBalasubramaniyam/ice-cream-parlour-website#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There  search bar on products page is not looks good .

![Screenshot 2024-10-19 000402](https://github.com/user-attachments/assets/a2d7e405-3be8-45d7-9e1a-da7840d5b425)

### Use Case

I' would  like to enhance the search bar on products page which looks similar with website.

Like This:
Which looks similar with as search bar of other page of website.

![Screenshot 2024-10-19 001307](https://github.com/user-attachments/assets/039a4d85-5a8e-40cf-aceb-aa62cd2f2dc2)

### Benefits

User can easily search their products and add to cart.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [ x\] I'm willing to provide further clarification or assistance if needed.

**Comment by Sudhanshu248** [comment]
@DharshiBalasubramaniyam Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by DharshiBalasubramaniyam** [comment]
Pls place the search bar below the category filter.
