### ISSUE TITLE
improve navbar design

### ISSUE THREAD

**Issue by sanayamahajan-23** [DharshiBalasubramaniyam/ice-cream-parlour-website#7]
the navbar design looks really basic so would improve it.

**Comment by sriraghavi22** [comment]
Hey could you assign this to me, I would love to work on this?

**Comment by riyarane46** [comment]
@sanayamahajan-23 , i believe i would resolve this issue . i have a strong background in css and html so i can style it .
GSSoc24 Extd.

**Comment by sanayamahajan-23** [comment]
But I have myself strong background and even contributed in gssoc 24 so I would like to work on it myself

**Comment by AkankshaSinghK** [comment]
Can i improve the navbar design as scrolling the links should get active according to page.
Can you please assign this issue to me.

**Comment by Gahlotkumkum** [comment]
Assign me, i can easily do this and make it more beautiful and responsive!!

**Comment by Antima2004** [comment]
hey,
please assign this to me.

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue , as I have a strong background in CSS and HTML. Please assign me under GSSOC'24 extended
