### ISSUE TITLE
[Bug]: Top scroll bar indicator missing in several html pages

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#706]
Add top scroll bar indicator in missing html files.

How to achive this.

in html body under preloader copy below code.

```
 <!-- scroll progress -->`
    <div class="scroll-progress"></div>
```

In header add css
`<link rel="stylesheet" href="styles/topscrollindicator.css">`

In body lastly add below script:
`<script src="script/topscrollindicator.js"></script>`

Kindy make sure the scroll bar is working in all pages.

**Comment by Abankita** [comment]
@DharshiBalasubramaniyam please assign me this issue. I want to work on this.

**Comment by Rohit72099** [comment]
Can I work on this issue

**Comment by harshpardeshi09** [comment]
@DharshiBalasubramaniyam Kindly assign me this issue as i will follow your instructions you mentioned above
