### ISSUE TITLE
Privacy page style missing

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#707]
Add below style link in the `privacy.html`
`<link rel="stylesheet" href="styles/styles.css">`

**Comment by SandhyaSankararaman** [comment]
Hi @DharshiBalasubramaniyam I would like to work on this issue. It would be great if you could assign it under gssoc-ext and hacktoberfest2024 along with the labels

**Comment by SandhyaSankararaman** [comment]
Thank you @DharshiBalasubramaniyam for Assigning this issue. I see that some styles for privacy page have been implemented. So, can you explain a bit more about what exactly needs to be done?

**Comment by DharshiBalasubramaniyam** [comment]
> Thank you @DharshiBalasubramaniyam for Assigning this issue. I see that some styles for privacy page have been implemented. So, can you explain a bit more about what exactly needs to be done?

just add that link in the header section.
