### ISSUE TITLE
Contact Us form need to fix

### ISSUE THREAD

**Issue by 4F24L** [DharshiBalasubramaniyam/ice-cream-parlour-website#71]
## Contact Us Form Need To Fix
- Should be in a box, So users can understand the form area
- Some impprovement needed

![image](https://github.com/user-attachments/assets/b56eb7df-e30e-4ff5-a996-92ad5a148857)

**Comment by 4F24L** [comment]
@DharshiBalasubramaniyam waiting to be assigned !

**Comment by T-Fathima** [comment]
I would like to work on it. Please assign it to me.
