### ISSUE TITLE
Contact Us Section

### ISSUE THREAD

**Issue by Bhum-ika** [DharshiBalasubramaniyam/ice-cream-parlour-website#715]
Before addressing the matter, I want to compliment your website for its beautiful design, attractive color combination, and minimalist effects.

![image](https://github.com/user-attachments/assets/786ef9c6-545f-447c-b1e3-bd1b8ed9f943)

But your contact form is spreading on whole area, an image can be added on side , and contact form can have a bg color .
These are some of the things. I will make it more appealing to align with your whole website

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
You will love the changes, for sure.

**Comment by DharshiBalasubramaniyam** [comment]
You can add an image on one side. But kindly dont change the bg color pls. leave it as white.

**Comment by Bhum-ika** [comment]
okay

**Comment by anchalchaturvedi08** [comment]
I want to work on this issue, will you assign me?
