### ISSUE TITLE
 enhance cart ui 

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#751]
I would like change the ui of the cart cards.

current:
![image](https://github.com/user-attachments/assets/d262a8dc-640b-452e-af09-4384438483b6)

expected:
![image](https://github.com/user-attachments/assets/b31329ce-1352-4d72-9144-b91fd9a4cba2)
The category name is not needed.

**Comment by mehendisil2004** [comment]
I can do this. Assign this work to me

**Comment by Utkarsha156** [comment]
I would like to work on this
Could you please assign it to me @DharshiBalasubramaniyam

**Comment by ayushgopal17** [comment]
can you assign me this @DharshiBalasubramaniyam

**Comment by kadambaridane** [comment]
Hey, Dharshi! Can you assigned me for this issue?

**Comment by mehendisil2004** [comment]
@DharshiBalasubramaniyam please look into the PR
