### ISSUE TITLE
Customer agreement page

### ISSUE THREAD

**Issue by Pushpa472** [DharshiBalasubramaniyam/ice-cream-parlour-website#763]
@DharshiBalasubramaniyam  Adding Customer agreement  page on clicking customer agreement. In the current site the link not working.
Make this link as workable and add customer agreement page.
![image](https://github.com/user-attachments/assets/cc25b6f0-a1fc-4dc7-972b-0f8f04453d8a)

**Comment by shauryaq05** [comment]
Please assign this task to me.
