### ISSUE TITLE
Different UI for Terms conditions and privacy policy

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [DharshiBalasubramaniyam/ice-cream-parlour-website#765]
Use same UI structure for both "Terms and conditions" and "privacy policy" pages. Currently both are different. 

![image](https://github.com/user-attachments/assets/b86147a4-efe2-468f-98df-6d0578cf5119)

![image](https://github.com/user-attachments/assets/ef1fcc90-00c7-47ff-93c6-cb3ca79b6092)

You can use existing style of one of them or your own one.

**Comment by Utkarsha156** [comment]
I would like to do it
Could you assign me this @DharshiBalasubramaniyam

**Comment by KartikSaxena19** [comment]
Can you please assign this task to me

**Comment by Utkarsha156** [comment]
@DharshiBalasubramaniyam please review the PR
