### ISSUE TITLE
display confirmation message after subscribed to newsletter section

### ISSUE THREAD

**Issue by Milsans** [DharshiBalasubramaniyam/ice-cream-parlour-website#77]
confirmation message is missing after subscribing newsletter section 
I want to add display feature of confirmation message. I am willing to fix it under gssoc and hacktober fest
![photo](https://github.com/user-attachments/assets/9d652c11-f1c7-41c5-ab5c-f55d2ab4e332)

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Milsans . Thank you for creating issue. But i think without the backend actual logic showing confirmation message is not appropriate.
