### ISSUE TITLE
[Feat]: Add a progress bar on the top of the navbar to make the website more attractive.

### ISSUE THREAD

**Issue by meetarora10** [DharshiBalasubramaniyam/ice-cream-parlour-website#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to add a progress bar on the top of the navbar of a suitable UI.

### Use Case

This will make the website more attractive.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shauryaq05** [comment]
Please assign this task to me.
