### ISSUE TITLE
Creating the website in dark mode

### ISSUE THREAD

**Issue by Haunter05** [DharshiBalasubramaniyam/ice-cream-parlour-website#79]
![Screenshot 2024-10-03 122431](https://github.com/user-attachments/assets/dc68e165-9af2-4793-b143-53c1d541bd80)
As the website is currently in light mode. I would like to add a button to switch the web to dark mode and hence converting the page in dark mode.

**Comment by DevSahil12** [comment]
can i work on this assignment

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Haunter05,Nice idea. But not needed for this website.
