### ISSUE TITLE
Upload a video of the website

### ISSUE THREAD

**Issue by Amulya-B28** [DharshiBalasubramaniyam/ice-cream-parlour-website#791]
I would like to upload a video of how the website works as a guide to the customers and the option available to the customer. Please assign this task to me. Thank you.

**Comment by Akanshaku** [comment]
I would like to work for this please assign me this @DharshiBalasubramaniyam

**Comment by Amulya-B28** [comment]
@Akanshaku Thank you for the help....but I can pull this off alone.
