### ISSUE TITLE
Implement Checkout with Stripe and 404 Page Not Found

### ISSUE THREAD

**Issue by SRV30** [DharshiBalasubramaniyam/ice-cream-parlour-website#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature request aims to implement a Checkout page that allows users to securely enter their payment information and complete their purchases through Stripe. Additionally, a user-friendly 404 Page Not Found will be created to handle instances where users navigate to non-existent routes within the application.

### Use Case

These enhancements will improve user satisfaction, boost sales, and create a more professional and reliable application overall.

### Benefits

These features enhance the project's functionality and reliability and contribute positively to user trust and community engagement, ultimately fostering a thriving user base.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by SRV30** [comment]
@DharshiBalasubramaniyam please assigned this to me

**Comment by DharshiBalasubramaniyam** [comment]
Checkout with strike not needed. You can create a not found page.

**Comment by SRV30** [comment]
@DharshiBalasubramaniyam thank u for assigning this to me. Sorry for late reply
