### ISSUE TITLE
Adding dark mode feature to website

### ISSUE THREAD

**Issue by shauryaq05** [DharshiBalasubramaniyam/ice-cream-parlour-website#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding dark mode feature for better night experience.

### Use Case

It increases the utility of the website.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by shivraj-yadav** [comment]
I would like to work on this project. Please assign it to me.
