### ISSUE TITLE
Improvement in About us section

### ISSUE THREAD

**Issue by Milsans** [DharshiBalasubramaniyam/ice-cream-parlour-website#81]
We can add some slider feature in about us section as added in review section to make more interactive home page 
I am willing to fix it under gssoc and hacktober fest. Please assign to me this task

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me under hactoberfest

**Comment by DharshiBalasubramaniyam** [comment]
Hi @Milsans. Nice idea. But not needed for this website.
