### ISSUE TITLE
[Feat]: Add Nutritional Information and Ingredients list

### ISSUE THREAD

**Issue by falak412** [DharshiBalasubramaniyam/ice-cream-parlour-website#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Nutritional Information & Ingredients
Nutritional Breakdown: Provide clear, detailed nutritional information (calories, sugar content, allergens, etc.) for each flavor.
Ingredient Transparency: List out all ingredients, sourcing information, and whether it’s organic, non-GMO, or fair-trade.
 Some customers need to avoid certain ingredients due to health conditions, allergies, or dietary preferences (e.g., vegan, gluten-free, sugar-free). So the feature is helpful for them.
@DharshiBalasubramaniyam please assign me this issue.
GSsoC'24 Extend Contributor

### Use Case

This feature will ensure that customer feels confident about the quality and suitability of the product.

### Benefits

Providing detailed information helps them easily navigate which products suit their needs, ensuring they feel safe and confident purchasing from your site. This can also broaden your customer base to include those with specific dietary restrictions.
By providing this information upfront, you reduce the number of customer service queries related to nutritional concerns, freeing up resources and improving overall efficiency.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Akanshaku** [comment]
I WOULD LIKE TO WORK ON THIS ISSUE PLEASE ASSIGN ME THIS.
