### ISSUE TITLE
[Bug]: Navbar of Gallery needs to improve or remove gallery menu

### ISSUE THREAD

**Issue by Rohit72099** [DharshiBalasubramaniyam/ice-cream-parlour-website#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened ?

[Bug]: Navbar of Gallery needs to improve or remove gallery menu

### Add Screenshots

![image](https://github.com/user-attachments/assets/85f65573-1c89-488f-85fd-5dd63d77c418)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DharshiBalasubramaniyam** [comment]
Kindly remove it
