### ISSUE TITLE
I would like to add a star rating system to each product

### ISSUE THREAD

**Issue by vararaghu002** [DharshiBalasubramaniyam/ice-cream-parlour-website#87]

**Comment by DharshiBalasubramaniyam** [comment]
Hi @vararaghu002 Can you share any sample ui from other websites

**Comment by vararaghu002** [comment]
Sure!

**Comment by vararaghu002** [comment]
I would like add rating like this way

**Comment by vararaghu002** [comment]
I would like add rating like this way
![IMG-20241004-WA0002](https://github.com/user-attachments/assets/bece7ba0-95a2-44c4-b87d-6aede7b63df9)

**Comment by DharshiBalasubramaniyam** [comment]
Okay. Update the product database to this purpose.
