### ISSUE TITLE
[Bug]: There are 2 logos on the website navbar

### ISSUE THREAD

**Issue by avogadroB** [DharshiBalasubramaniyam/ice-cream-parlour-website#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened ?

There are 2 logos side by side on the navbar

### Add Screenshots

![image](https://github.com/user-attachments/assets/58f0ef9b-1c79-41b4-bca3-1edaabd24dcd)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DharshiBalasubramaniyam** [comment]
Which page?

**Comment by avogadroB** [comment]
Hi, this problem was seen on on all the pages but is seems someone fixed that even if I can't see the issue any where. Now, the logos are misaligned now on different headers:

delivery:
![image](https://github.com/user-attachments/assets/6eb12293-f5ec-4871-8600-42e292b99f56)

home:
![image](https://github.com/user-attachments/assets/02d0f6c8-85e1-40c3-9ff0-33d6748ad876)

Do you want me to fix it under this issue itself?

**Comment by DharshiBalasubramaniyam** [comment]
That one is assigned to another one! Thankks.
