### ISSUE TITLE
X text  change / product not visible /  add icon X sign page 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [DharshiBalasubramaniyam/ice-cream-parlour-website#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

X Text Change: The text for an "X"   all Page 

Product Not Visible: A product or section of the page is hidden or not visible under certain conditions.

Add Icon X Sign: Adding an "X" icon to a page.

 
![Screenshot (393)](https://github.com/user-attachments/assets/2b86e9f0-ab8b-426f-af66-20b4aa0608ce)
![Screenshot (392)](https://github.com/user-attachments/assets/f966dcd3-445f-4318-9ed3-24d63d976d08)

### Use Case

n a web application, use the "X" icon to close popup notifications or messages, and dynamically change the accompanying text for better user experience.

### Benefits

Dynamic elements like the "X" icon and undo options make the page feel more interactive, keeping users engaged longer.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DharshiBalasubramaniyam** [comment]
Can you pls explain the issue clearly? I didn't get it

**Comment by RahulPrasadYadav** [comment]
@DharshiBalasubramaniyam  in footer section change the text (twitter) => (X)  and   sign up page add X icon you can sign up X icon
