### ISSUE TITLE
[Feat]: Cursor enchantment

### ISSUE THREAD

**Issue by nihalawasthi** [DharshiBalasubramaniyam/ice-cream-parlour-website#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 **Custom Cursor Appearance**: When the website loads, the default system cursor should either be hidden or replaced by a custom ice cream cone graphic. This change will ensure that the cursor matches the aesthetic of the site, offering a more immersive and personalized user experience.

### Use Case

A visitor browsing the website. Instead of a standard arrow cursor, they see an ice cream cone guiding their interactions. This adds a layer of thematic fun to the website and makes it feel more personalized and aligned with the content.

### Benefits

- **Visual Consistency**: This will prevent the system default cursor from conflicting with the visual design of the website, creating a cleaner and more cohesive look.
- **Branding and Aesthetic**: Using an ice cream cone cursor enhances the whimsical, playful aesthetic of the website, making the user experience more engaging and memorable.
- **Enhanced Engagement**: Unique cursor designs like this often catch the attention of visitors, keeping them engaged longer, which can lead to better retention and interaction with the website.

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by snehakaushik00** [comment]
i would like to work on this issue . please assign this to me.

**Comment by shreya2k3** [comment]
@DharshiBalasubramaniyam can you please assign this issue to me?

**Comment by nihalawasthi** [comment]
@shreya2k3  if you want to contribute to a project you have to create a issue and then wait for approval from Author
the project will be assigned to whoever created the issue

**Comment by nihalawasthi** [comment]
@DharshiBalasubramaniyam
so which option do you want me to proceed with 
- no cursor just animations
- custom icecream cursor
