### ISSUE TITLE
[Feat]: Adding a Close (X) Button to Pop-Up on Landing Page

### ISSUE THREAD

**Issue by khushi1315** [DharshiBalasubramaniyam/ice-cream-parlour-website#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently landing on the page, pop-up can be dismissed on clicking "No Thanks". For better user experience, I want to add a close button on top right corner of pop-up.
Kindly Assign me this work under gssoc-ext ,hacktoberfest and level of your choice.

### Use Case

1. User Retention:
 Users frustrated by difficult-to-close pop-ups are more likely to leave the site. A close button can help retain users by reducing such frustration.

2.Feedback and Engagement:
Higher Engagement: Users who can easily dismiss a pop-up may be more willing to engage with the site content rather than leaving the site or ignoring further interactions.

### Benefits

1. Improved User Experience:

- Ease of Use: Users can quickly and intuitively close the pop-up without searching for the "No thanks" button.

- Control: Gives users more control over their interaction with the site, making the experience smoother and less frustrating.

2.Accessibility:

Inclusivity: Not all users are comfortable or able to find and click a small link or button like "No thanks". A clearly marked close button is a more inclusive solution.

3.Professional Look:

- UI Consistency: Having a standard close (X) button aligns with common UI practices, making the design appear more professional and polished.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Shalinis19137** [comment]
I really like your application and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by khushi1315** [comment]
@Shalinis19137 If you want to work on the project kindly raise a new issue. If manager assigns you work then you start working on it.

**Comment by sameer-soni** [comment]
@DharshiBalasubramaniyam If there is no update, can i get assigned?

**Comment by khushi1315** [comment]
@sameer-soni I have been assigned this work and completed it .I am waiting for the work to be reviewed. You can search for another issue.
