### ISSUE TITLE
[Bug]:in  footer  section text and icon overwrite for mac's and ipad

### ISSUE THREAD

**Issue by adityalaxkar123** [DharshiBalasubramaniyam/ice-cream-parlour-website#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened ?

In footer section icon and text is overwrite for mac's and ipad

### Add Screenshots

![IMG_20241026_175741](https://github.com/user-attachments/assets/6dc1c355-ea1f-4379-9ead-422993fd1fcf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DharshiBalasubramaniyam** [comment]
Pls remove those icons
