### ISSUE TITLE
"Find the nearest store to you" button in services section has font color different from others

### ISSUE THREAD

**Issue by nishtha-902** [DharshiBalasubramaniyam/ice-cream-parlour-website#94]
"Find the nearest store to you" button must have yellow color, but it's blue which not according to theme and breaking symmetry. please assign me this issue, I will change that color so that symmetry is maintained.

**Comment by dnyanesh99borse** [comment]
AS A EXPERIENCED FRONTEND DEVELOPER , I CAN RESOLVE THIS ISSUE VERY EFFECTIVELY AND CAN ENHANCE THE BUTTON TO THE NEXT LEVEL BY 10X. SO I HUMBLY REQUEST TO YOU TO PLEASE ASSIGN THIS TASK TO ME TOO. AND BELEIVE YOUR TRUST WILL BE DEFINATELY VALUABLE. I HOPE YOU WILL.... ~thankyou

**Comment by sahare-mayur-007** [comment]
"Find the nearest store to you" button must have yellow color, but it's blue which not according to theme and breaking symmetry. please assign me this issue, I will change that color so that symmetry is maintained.
