### ISSUE TITLE
[Feat]: Search button...

### ISSUE THREAD

**Issue by Hemraj-7** [DharshiBalasubramaniyam/ice-cream-parlour-website#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Search button are not looking good in the Dine-in page and Our Products page. In small devices like mobile phones

![Screenshot 2024-10-27 143442](https://github.com/user-attachments/assets/b4199a3f-3d61-46b1-b195-458d52bfd66f)  
![Screenshot 2024-10-27 143504](https://github.com/user-attachments/assets/10c6e799-1a2b-4c19-8e8e-a107e08baf22)

Assign me this issue
thank you!

### Use Case

For better user Experience

### Benefits

For better user Experience

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Hemraj-7** [comment]
Hey! @DharshiBalasubramaniyam , the search bar and search button height is different different.

![Screenshot 2024-10-27 151733](https://github.com/user-attachments/assets/f151e4df-6194-47e8-9f9f-9b7d4a78fc8c)
 
I think should both be same height.
What is your opinion? it is okey

**Comment by Divyansh8843** [comment]
@DharshiBalasubramaniyam I want to contribute on this issue. please assign this issue to me.
