### ISSUE TITLE
[Bug]: Checkbox Should Select When Clicking Text

### ISSUE THREAD

**Issue by RajputSneha17** [DharshiBalasubramaniyam/ice-cream-parlour-website#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened ?

When clicking the text next to the checkbox (or radio button), it does not get selected. It would be easier for users if the checkbox/radio button could be checked by clicking the text as well. Currently, it only works when clicking directly on the button.

### Before:
https://github.com/user-attachments/assets/665b4d22-3ecc-478a-840b-8e878a9e9138

###After:

https://github.com/user-attachments/assets/6b4bb97f-a212-4b2d-8c96-a6d3840c9641

### What browsers are you seeing the problem on?

Google Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by iamprathama** [comment]
i am want to fix this issue

**Comment by iamprathama** [comment]
![Uploading Screenshot 2024-10-28 105208.png…]()
