### ISSUE TITLE
[Bug]: Unnecessary Capitalization in Form Labels (delivery.html)

### ISSUE THREAD

**Issue by DevStudyBug** [DharshiBalasubramaniyam/ice-cream-parlour-website#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened ?

In the delivery.html form, certain labels such as "CONTACT No." and "ADDRESS Line2" use inconsistent capitalization, which can affect the readability and visual consistency of the form.

This issue can be solved by the capitalization across all form labels. Suggested changes include:

CONTACT No. → Contact No.
ADDRESS Line2 → Address Line 2
This improvement will ensure a cleaner and more user-friendly design throughout the form. Please assign this issue to me @<DevStudyBug>.

### Add Screenshots

![image](https://github.com/user-attachments/assets/1dee84cd-e1c7-4550-82fd-940e7fdd201a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Gungunmi12** [comment]
i want to work on this issue please assign it to me

**Comment by DevStudyBug** [comment]
Issue resolved! Standardized the capitalization in form labels on delivery.html. 🎉
- PR Linked: [#978](https://github.com/DharshiBalasubramaniyam/ice-cream-parlour-website/pull/978)
