### ISSUE TITLE
To adding the animation effect to social media icons

### ISSUE THREAD

**Issue by Sujal1201** [DharshiBalasubramaniyam/ice-cream-parlour-website#976]
## issue: animation effect on social media icons

**screenshot**

<img width="139" alt="image" src="https://github.com/user-attachments/assets/2c6eff17-148b-4520-adbb-3bdadb7e7723">

**Comment by Sujal1201** [comment]
please assign me to this issue

**Comment by Gungunmi12** [comment]
please assign it to me
