### ISSUE TITLE
[Bug]: Incorrect Mapping of State Dropdown Options in Delivery Form (delivery.html)

### ISSUE THREAD

**Issue by DevStudyBug** [DharshiBalasubramaniyam/ice-cream-parlour-website#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened ?

There’s an issue with the state dropdown options in your code. Currently, the dropdown is showing locations in Sri Lanka, but each option has been incorrectly labeled with a corresponding state in India (e.g., "Andhra Pradesh" for "Colombo").

### Add Screenshots

![image](https://github.com/user-attachments/assets/bad84368-c793-45ed-af74-a6f52289b0e1)
![image](https://github.com/user-attachments/assets/6fd53fe4-1b9a-483d-8a8b-aaa49bad5456)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by DharshiBalasubramaniyam** [comment]
Pls replace the value attribute with coresponding sri lanka state name.

**Comment by DevStudyBug** [comment]
@DharshiBalasubramaniyam Could you please add the "hacktoberfest-accepted" label to my pull request so it can count towards Hacktoberfest?
